### PR TITLE
task/selinux: Fix regressed grepping of audit logs

### PR DESCRIPTION
**Pull request by zmc**
This was broken by a106217.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
Testing at https://pulpito.ceph.com/zack-2023-01-30_19:52:21-crimson-rados-main-distro-default-smithi/

**Review by athanatos — APPROVED** [review]

**Comment by athanatos** [comment]
I think it would be helpful to have Fixes: <tracker link> in the commit message.

**Comment by zmc** [comment]
> I think it would be helpful to have Fixes: in the commit message.

Great point. I'll re-push once the suite yields some results

**Comment by ljflores** [comment]
Is this the run we're using to validate?

https://pulpito.ceph.com/zack-2023-01-30_19:52:21-crimson-rados-main-distro-default-smithi/

**Comment by athanatos** [comment]
Yeah, you can ignore anything that isn't an selinux failure.

**Comment by ljflores** [comment]
So far, no selinux failures.

**Review by ljflores — APPROVED** [review]

**Comment by zmc** [comment]
Now we're running:
```sudo grep -a 'avc: .*denied' /var/log/audit/audit.log | grep -av -e 'comm="dmidecode"' -e chronyd.service -e 'name="cephtest"' -e scontext=system_u:system_r:nrpe_t:s0 -e scontext=system_u:system_r:pcp_pmlogger_t -e scontext=system_u:system_r:pcp_pmcd_t:s0 -e 'comm="rhsmd"' -e scontext=system_u:system_r:syslogd_t:s0 -e tcontext=system_u:system_r:nrpe_t:s0 -e 'comm="updatedb"' -e 'comm="smartd"' -e 'comm="rhsmcertd-worke"' -e 'comm="setroubleshootd"' -e 'comm="rpm"' -e tcontext=system_u:object_r:container_runtime_exec_t:s0 -e 'comm="ksmtuned"' -e 'comm="sssd"' -e 'comm="sss_cache"' -e context=system_u:system_r:NetworkManager_dispatcher_t:s0```

And to me, it looks correct. We can wait until the rest of the run finishes - or not - but I'll un-Draft this now.

**Comment by athanatos** [comment]
Previously, they were almost all failing.  This is probably sufficient.

**Review by athanatos — APPROVED** [review]

**Pull request merged**
