### PR TITLE
Fixing small typo

### PR DESCRIPTION
**Pull request by ivotron**
Changing from `dsa` to `dss` in error message.

### CODE REVIEW

**Comment by dmick** [comment]
was surprised to see this; found http://security.stackexchange.com/questions/51567/why-are-dsa-keys-referred-to-as-dss-keys-when-used-with-ssh; I actually think ssh is contributing to confusion here.  I'd advise using "or ssh-dss (DSA)"  to avoid confusing people with a similar level of partial knowledge, since the key types are really RSA and DSA, despite the label ssh-dss.

What do you think?

**Comment by ivotron** [comment]
I think either is fine, as long as there's consistency between the message
and the config. I agree that DSA makes more sense but changing it will
break existing yaml config files.

**Comment by dmick** [comment]
?  No, I'm talking about changing the error message from your suggested 'keytype must be ssh-rsa or ssh-dss' to 'keytype must be ssh-rsa or ssh-dss (DSA)'

**Comment by ivotron** [comment]
Sorry Dan, I somehow misread your first message (too tired I guess). I
agree, will change it the way you suggest.

**Comment by ivotron** [comment]
done

**Pull request merged**
