### PR TITLE
[DNM] Wip ceph ansible

### PR DESCRIPTION
**Pull request by vasukulkarni**
Still in testing, 

Waiting on: http://tracker.ceph.com/issues/16818

### CODE REVIEW

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
@vasukulkarni any update on this? Should we really block this on that bug you mentioned?

**Comment by vasukulkarni** [comment]
@zmc , @andrewschoen fixed that with https://github.com/ceph/ceph-ansible/pull/1065 and the later reruns with wip-ceph-ansible2 teuthology branch worked and needs some more minor updates for workunits to work http://pulpito.ceph.com/vasu-2016-11-10_03:32:39-smoke:ceph-ansible-jewel---basic-vps/

**Comment by zmc** [comment]
@vasukulkarni ok - are you saying that this PR is obsolete and there will be a replacement?

**Comment by vasukulkarni** [comment]
@zmc sure I think i will close this one instead of force push here and open that one.

**Comment by vasukulkarni** [comment]
closing for https://github.com/ceph/teuthology/pull/995

**Pull request closed without merging**
