### PR TITLE
add stop_worker: as a mean to shutdown the worker

### PR DESCRIPTION
**Pull request by dachary**
It is convenient for integration tests as a way for the worker to be
instructed to shutdown cleanly.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
test this please

**Comment by zmc** [comment]
This seems like it would be awkward to use. Why not intercept a signal telling the worker to stop after the current job is finished?

**Comment by dachary** [comment]
This is how I'm using it in the context of integration tests for the OpenStack backend: https://github.com/dachary/teuthology/blob/wip-6502-openstack/teuthology/test/integration/noop.yaml . The sequence is (as implemented at https://github.com/dachary/teuthology/blob/wip-6502-openstack/teuthology/test/integration/openstack-integration.py#L76 )

* run the worker as a subprocess, 
* schedule the job including "stop_worker", 
* wait for the worker to finish

The alternative would be to poll the worker to figure out when the job finishes. I'm not sure there is a convenient way to do that ? Another option would be to add an option to the working to tell it to run X jobs at most and stop.

**Comment by zmc** [comment]
@dachary could you rebase this please? I can merge it once that's done.

**Comment by dachary** [comment]
rebased & repushed !

**Pull request merged**
