### PR TITLE
 fix nuke

### PR DESCRIPTION
**Pull request by vasukulkarni**
Tested this on some of the nodes which weren't cleaning up before due to bad package state, this works fine on both rhel and ubuntu, Since I have updated paramiko I will be testing this with few test suites to ensure everything works.

### CODE REVIEW

**Comment by zmc** [comment]
A couple things:
``remove_ceph_packages`` and the timeout changes should be separate commits
Unpinning ``paramiko`` will require fairly extensive testing; attempting to unpin it in the past hasn't worked out well.

**Comment by vasukulkarni** [comment]
@zmc I can pin it to specific stable version since we are using quite old version now, I will be running full rados and other suites, will make the other changes you said.

**Comment by zmc** [comment]
@vasukulkarni Looking forward to seeing your test results - I'd love to be able to just use the latest version.

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2016-03-30_18:27:23-rados-jewel---basic-mira/
http://pulpito.ceph.com/vasu-2016-03-30_17:17:04-rados-jewel---basic-vps/
http://pulpito.ceph.com/vasu-2016-03-30_17:21:17-rados-jewel---basic-mira/

Some more runs in progress...

**Comment by vasukulkarni** [comment]
@zmc This has passed powercycle suite with no failures, can't find my link on pulpito.ceph.com, I have been using this extensively on all my runs with no issues.

**Comment by yonghengdexin735** [comment]
@vasukulkarni 
 I  meet a problem that  when the test failure, the testnodes couldn't nuke like:
teuthology.nuke:Could not nuke {'ubuntu@plana112.example.com': u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCg5k4qSPUsnrs4lgr4ib8w5+Nb/+mgB8yU3fHkVHefnMBKSxwdJMT9cxBugkwIjX/uHcuLbjsMiUCrL88DpztcZ88c+8BnQ/uM4C+GF+PcWEXBc0ofD/+/KDWCULsuwzvsSMPrf96zC8f5ZvZGer9jchhLt1Aro/TWMO5l3zbD4GopBfWq9QhkHyLB/f6dWmxXIpnLBoQVPXk+zFOpy8jxIxRvwgXhz8RX5WsPPNawntcKQkV6v0IvO4AQpxGRqskfrSgBIQQwPal94PRrrnf/vRpSd2/eKnbh2RvVUuOUKs8V1dJyVSq16HTr68TTHI4/a5fUZqb2d2PJxUnVx4Wz'}.
if I comments all your changes like:'timeout',it will be ok.
I guess if the version of  the paramiko is too old, but how to update it in virtualenv？ thanks

**Pull request merged**
