### PR TITLE
Add teuthology-wait command

### PR DESCRIPTION
**Pull request by kshtsk**

### CODE REVIEW

**Review by vasukulkarni — APPROVED** [review]

**Comment by vasukulkarni** [comment]
Is there a test output from this CLI?

**Comment by kshtsk** [comment]
> Is there a test output from this CLI?

I was testing it locally but I can make another example.

**Comment by kshtsk** [comment]
But it is basically equivalent to what we have when running teuthology-suite with the -w option

**Comment by kshtsk** [comment]
Here is an example of scheduling
```
~/teuthology> teuthology-suite         --machine-type ecp                  --suite-repo http://github.com/SUSE/ceph         --suite-branch wip-ses7-qa-add-node         --ceph-repo http://github.com/SUSE/ceph         --ceph ses7         --suite suse:tier1         --filter-all sle,add-node         --kernel none                  /home/runner/overrides-artifacts-storage-ci-teuthology-deepsea-smoke-devel-7.0-build-332.yaml --rocketchat @kshatskyy
2020-12-14 19:22:18,646.646 INFO:teuthology.suite:Using random seed=413
warning: redirecting to https://github.com/SUSE/ceph/
2020-12-14 19:22:19,351.351 INFO:teuthology.suite.run:ceph sha1: 56fc3dd5b9140b9742563f804e989695a29183b3
2020-12-14 19:22:19,352.352 INFO:teuthology.suite.run:skipping ceph package verification
warning: redirecting to https://github.com/SUSE/ceph/
warning: redirecting to https://github.com/SUSE/ceph/
2020-12-14 19:22:20,674.674 INFO:teuthology.suite.run:ceph branch: wip-ses7-qa-add-node c19eb8ba56c5eb46594b8c7a46033c3c6bc6cb38
2020-12-14 19:22:20,676.676 INFO:teuthology.repo_utils:/home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node was just updated; assuming it is current
2020-12-14 19:22:20,677.677 INFO:teuthology.repo_utils:Resetting repo at /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node to branch origin/wip-ses7-qa-add-node
2020-12-14 19:22:21,312.312 INFO:teuthology.suite.run:teuthology branch: master a4989a90c28c6c875dcbb068b72ed22103535745
2020-12-14 19:22:21,382.382 INFO:teuthology.suite.run:Suite suse:tier1 in /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node/qa/suites/suse/tier1 generated 4 jobs (not yet filtered)
Job scheduled with name kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp and ID 577
2020-12-14 19:22:22,799.799 INFO:teuthology.suite.run:Scheduling suse:tier1/add-node/{0-salt 1-deploy-phase boilerplate/{ceph_cm} cluster/{4disks roles} distros/sle_15.2}
Job scheduled with name kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp and ID 578
2020-12-14 19:22:24,232.232 INFO:teuthology.suite.run:Suite suse:tier1 in /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node/qa/suites/suse/tier1 scheduled 1 jobs.
2020-12-14 19:22:24,233.233 INFO:teuthology.suite.run:3/4 jobs were filtered out.
Job scheduled with name kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp and ID 579
2020-12-14 19:22:25,599.599 INFO:teuthology.suite.run:Test results viewable at http://teuth-ses.prv.suse.net:8081/kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp/
```
and waiting
```
~/teuthology> teuthology-wait -r kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp ; echo $?
2020-12-14 19:23:02,042.042 INFO:teuthology.suite:waiting for the run kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp to complete
2020-12-14 19:38:02,174.174 INFO:teuthology.suite:wait is done
2020-12-14 19:38:02,197.197 INFO:teuthology.suite:pass http://teuth-ses.prv.suse.net/teuthology/kyr-2020-12-14_19:22:18-suse:tier1-ses7-none-basic-ecp/578/teuthology.log suse:tier1/add-node/{0-salt 1-deploy-phase boilerplate/{ceph_cm} cluster/{4disks roles} distros/sle_15.2}
0
```

**Comment by kshtsk** [comment]
and example for dead/failed job waiting:
```
~/teuthology> teuthology-suite         --machine-type ecp                  --suite-repo http://github.com/SUSE/ceph         --suite-branch wip-ses7-qa-add-node         --ceph-repo http://github.com/SUSE/ceph         --ceph ses7         --suite suse:tier1         --filter-all sle,add-node         --kernel none                  /home/runner/overrides-artifacts-storage-ci-teuthology-deepsea-smoke-devel-7.0-build-332.yaml --rocketchat @kshatskyy
2020-12-14 19:45:46,948.948 INFO:teuthology.suite:Using random seed=3677
warning: redirecting to https://github.com/SUSE/ceph/
2020-12-14 19:45:47,655.655 INFO:teuthology.suite.run:ceph sha1: 56fc3dd5b9140b9742563f804e989695a29183b3
2020-12-14 19:45:47,656.656 INFO:teuthology.suite.run:skipping ceph package verification
warning: redirecting to https://github.com/SUSE/ceph/
warning: redirecting to https://github.com/SUSE/ceph/
2020-12-14 19:45:49,228.228 INFO:teuthology.suite.run:ceph branch: wip-ses7-qa-add-node c19eb8ba56c5eb46594b8c7a46033c3c6bc6cb38
2020-12-14 19:45:49,237.237 INFO:teuthology.repo_utils:Fetching wip-ses7-qa-add-node from origin
2020-12-14 19:45:50,049.049 INFO:teuthology.repo_utils:Resetting repo at /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node to branch origin/wip-ses7-qa-add-node
2020-12-14 19:45:50,700.700 INFO:teuthology.suite.run:teuthology branch: master a4989a90c28c6c875dcbb068b72ed22103535745
2020-12-14 19:45:50,740.740 INFO:teuthology.suite.run:Suite suse:tier1 in /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node/qa/suites/suse/tier1 generated 4 jobs (not yet filtered)
Job scheduled with name kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp and ID 587
2020-12-14 19:45:52,080.080 INFO:teuthology.suite.run:Scheduling suse:tier1/add-node/{0-salt 1-deploy-phase boilerplate/{ceph_cm} cluster/{4disks roles} distros/sle_15.2}
Job scheduled with name kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp and ID 588
2020-12-14 19:45:53,523.523 INFO:teuthology.suite.run:Suite suse:tier1 in /home/kyr/src/github.com_SUSE_ceph_wip-ses7-qa-add-node/qa/suites/suse/tier1 scheduled 1 jobs.
2020-12-14 19:45:53,524.524 INFO:teuthology.suite.run:3/4 jobs were filtered out.
Job scheduled with name kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp and ID 589
2020-12-14 19:45:54,887.887 INFO:teuthology.suite.run:Test results viewable at http://teuth-ses.prv.suse.net:8081/kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp/
```
and actual waiting:
```
~/teuthology> teuthology-wait -r kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp ; echo $?
2020-12-14 19:46:17,550.550 INFO:teuthology.suite:waiting for the run kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp to complete
2020-12-14 19:51:17,635.635 INFO:teuthology.suite:wait is done
2020-12-14 19:51:17,672.672 INFO:teuthology.suite:dead http://teuth-ses.prv.suse.net/teuthology/kyr-2020-12-14_19:45:46-suse:tier1-ses7-none-basic-ecp/588/teuthology.log suse:tier1/add-node/{0-salt 1-deploy-phase boilerplate/{ceph_cm} cluster/{4disks roles} distros/sle_15.2}
1
```

**Comment by kshtsk** [comment]
And here is an example of verbose log:
```
~/teuthology> teuthology-wait -vr kyr-2020-12-14_20:00:05-suse:tier1-ses7-none-basic-ecp
2020-12-14 20:02:14,140.140 INFO:teuthology.suite:waiting for the run kyr-2020-12-14_20:00:05-suse:tier1-ses7-none-basic-ecp to complete
2020-12-14 20:02:14,141.141 DEBUG:teuthology.suite:the list of unfinished jobs will be displayed every 5.0 minutes
2020-12-14 20:07:14,183.183 DEBUG:teuthology.suite:wait for jobs ['591']
2020-12-14 20:12:14,207.207 DEBUG:teuthology.suite:wait for jobs ['591']
2020-12-14 20:12:14,229.229 INFO:teuthology.suite:wait is done
2020-12-14 20:12:14,252.252 INFO:teuthology.suite:pass http://teuth-ses.prv.suse.net/teuthology/kyr-2020-12-14_20:00:05-suse:tier1-ses7-none-basic-ecp/591/teuthology.log suse:tier1/add-node/{0-salt 1-deploy-phase boilerplate/{ceph_cm} cluster/{4disks roles} distros/sle_15.2}
~/teuthology> echo $?
0
```

**Pull request merged**
