### PR TITLE
Allow both $ and directory$ for random yamls.

### PR DESCRIPTION
**Pull request by wusui**
If either the diretory contains a magic $ file, or if the directory name
ends with $, then the random selection of a yaml file will occur.

Signed-off-by: Warren Usui <wusui@redhat.com>

### CODE REVIEW

**Comment by wusui** [comment]
This change implements the 'choose a random yaml file' behavior both for magic $ files and for directory names that end with $.   The following is an example of the directory$ behavior.

foo is a directory containing distro definitions -- yaml files that define os_type and os_version. The files in foo are:
%
ubuntu.yaml
centos.yaml
rhel.yaml

A suite that links distros to foo will run a test for ubuntu, centos, and rhel.

A suite that links distros$ to foo will run a test, randomly selecting from ubuntu, centos and rhel.

This would allow a suite of n combinations of tests to run roughly n/3 tests on each distro when distro$ is used as the name of the symbolic link. When distro is the name of the symbolic link 3*n tests will be run (once for each yaml file).

**Comment by wusui** [comment]
I was trying to remove a commit from wip-wusui2 and that pull request ended up getting closed by me.  So I cloned the latest teuthology and put those changes on this one.

**Comment by wusui** [comment]
test me please

**Comment by wusui** [comment]
While I was working with the previous pull request for this, it somehow closed (I put in a test for jenkins to run and tried to back it out and I am not sure what happened).   I have since placed the changes in another branch.

Right now one of the unittests for the directory$ changes that I added is failing.  I don't know why.  I ran the tests manually, and it seemed to work there.

Zack:  Is this a reasonable way of running the tests manually?

python
>>> from test_build_matrix import TestBuildMatrix
>>> x=TestBuildMatrix()
>>> x.setup()
>>> x.test_random_dollar_sign_with_convolve()

**Comment by yuriw** [comment]
test this please

**Comment by wusui** [comment]
https://jenkins.ceph.com/job/teuthology-pull-requests/1168/consoleFull#842358957c212b007-e891-4176-9ee7-2f60eca393b7

After looking at this, it appears that the problem is unrelated to my changes.  I am going to run again with my full version, git squash, and look into this further.

**Comment by zmc** [comment]
I'm confused about these failures as well; I can't reproduce locally. I'm going to rerun them here.

**Comment by zmc** [comment]
test this please

**Comment by wusui** [comment]
test me please

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
@wusui @zmc at what point we either merge it with failing test or give up ?

**Comment by wusui** [comment]
test me please

**Comment by zmc** [comment]
@wusui test failures: https://paste.fedoraproject.org/paste/mns~VzOgRgfi0~L-KxPKyw

**Comment by wusui** [comment]
test me please

**Comment by wusui** [comment]
I tried rebasing but my local copy got all weird.  I think that this is ready for review.

**Comment by zmc** [comment]
@wusui this looks good! Do you need help rebasing?

**Comment by wusui** [comment]
I may need help rebasing.  I tried, and got a 'no branch, rebasing wip-wusui-23208' entry.  After I continued, I ended up with an entry in the git log that said: "Merge branch 'wip-wusui-23208' of http://github.com/ceph/teuthology into wip-wusui-2320" but git diff showed did not do anything.

**Comment by wusui** [comment]
Note: In addition to rebasing I am also trying to squash a bunch of commits.

**Comment by zmc** [comment]
@wusui I just rebased and pushed for you. I want to let you squash, so if you local clone is busted, maybe try from a new one?

**Comment by wusui** [comment]
Okay.  I'll try squashing with a new clone.

**Comment by wusui** [comment]
I squashed and the last test passed.

**Comment by zmc** [comment]
@wusui this isn't actually squashed

**Comment by wusui** [comment]
Okay.  I think that it is squashed now.

**Pull request merged**
