### PR TITLE
task.kernel: Only show latest kernel when running rpm -q kernel

### PR DESCRIPTION
**Pull request by djgalloway**
Fixes: http://tracker.ceph.com/issues/23381

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@djgalloway this task for distro option needs to be revisited, we have an existing task for redhat, probably it can use be used for all rpm systems https://github.com/ceph/teuthology/blob/master/teuthology/task/kernel.py#L459 but centos will still fail..

The kernel tasks are still run with custom kernel as many other upstream kernels are behind so ...

**Comment by djgalloway** [comment]
Does that task get run before or after ceph-cm-ansible?

**Comment by tchaikov** [comment]
retest this please.

**Comment by vasukulkarni** [comment]
@zmc @djgalloway was this tested with kernel task to see if its working as expected? the issue we have in tracker is due to run on a distro kernel instead of test kernel and doesn't fully address the problem.

**Pull request merged**
