### PR TITLE
nuke: Tolerate null node description

### PR DESCRIPTION
**Pull request by zmc**
Fixes a TypeError

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
> I know that this definitely works, but would `status.get('description')` by itself with the default value being `None` work as well?

That would just result in `TypeError: argument of type 'NoneType' is not iterable` instead of a `KeyError` if there were no description

**Review by kamoltat — DISMISSED** [review]
should have been approved a long time ago.

**Comment by kamoltat** [comment]
jenkins retest this please

**Review by VallariAg — DISMISSED** [review]

**Review by VallariAg — APPROVED** [review]

**Review by kamoltat — APPROVED** [review]
LGTM

**Pull request merged**
