### PR TITLE
Wip schedule -- with fix for 11533

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by athanatos** [comment]
Hopefully now with less fail.

**Comment by athanatos** [comment]
Repushed with the fix in its own commit.

**Comment by zmc** [comment]
I just tested this manually, starting with current ``master`` and:
1. cherry-picking the commit with the unit test
2. running all the ``teuthology-suite`` unit tests (all passed)
3. cherry-picking the main ``--subset`` commit
4. rerunning unit tests (the new one failed)
5. cherry-picking the fix commit
6. rerunning unit tests (they passed again)

**Comment by andrewschoen** [comment]
LGTM

**Pull request merged**
