### PR TITLE
task/kernel: fix Depends: parsing for dependencies with "|"

### PR DESCRIPTION
**Pull request by dmick**
also make the "Checking kernel version...want" logmsg include quotes
for spotting problems more quickly

Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
This should fix the failures on Ubuntu 16.04 noticed today

**Comment by dmick** [comment]
Tested with
```
interactive-on-error: true
nuke-on-error: false
kernel:
   sha1: distro
roles:
  - [client.0]

tasks:
  - interactive:
```

**Comment by yuriw** [comment]
@dmick @liewegas suspect this PR caused http://tracker.ceph.com/issues/38802

**Comment by dmick** [comment]
No, this PR should have *fixed* 38802, but you have to pick up the new code

**Pull request merged**
