### PR TITLE
Drop teuthology-coverage command

### PR DESCRIPTION
**Pull request by toabctl**
It seems to be unused and there was no change in the last 6 years. I
guess it's not used and not needed so drop it to remove the dead
code.

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

### CODE REVIEW

**Comment by toabctl** [comment]
@kshtsk any comments here?

**Comment by kshtsk** [comment]
> @kshtsk any comments here?

coverage stuff is out of my knowledge, I thought it is used by someone, at least I'm trying to not break it and keep all components "working"

**Comment by toabctl** [comment]
@tchaikov do you know if coverage is still in use?

**Comment by tchaikov** [comment]
@toabctl i think Josh is author of these scripts, and since he is fine with this. we can drop it. if there is any needs, we can always revive this feature.

**Pull request merged**
