### PR TITLE
Support fetching packages from shaman instead of gitbuilder

### PR DESCRIPTION
**Pull request by zmc**
Note that this PR does not add shaman support to the kernel task, as we're not building kernels with chacra yet.

### CODE REVIEW

**Comment by zmc** [comment]
Let's schedule some test runs.
```
$ cat shaman.yaml
use_shaman: true
```
* [```teuthology-suite -v -c jewel -s smoke -m vps -v -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com -d ubuntu -D 16.04 -l 3 --filter-out ceph-deploy  $PWD/shaman.yaml```](http://pulpito.ceph.com/zack-2016-09-13_16:40:16-smoke-jewel-distro-basic-vps/)
* [```teuthology-suite -v -c jewel -s smoke -m vps -v -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com -d ubuntu -D 16.04 -l 3 --filter-out ceph-deploy```](http://pulpito.ceph.com/zack-2016-09-13_16:40:50-smoke-jewel-distro-basic-vps/)

**Comment by zmc** [comment]
The build missing the ``libcephfs-java`` package is [here](https://1.chacra.ceph.com/r/ceph/jewel/9bfc0cf178dc21b0fe33e0ce3b90a18858abaf1b/ubuntu/xenial/flavors/default/), but in the last couple hours it has disappeared entirely, even though it is still referred to by [this shaman query](https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros=ubuntu%2F16.04%2Fx86_64&ref=jewel&sha1=9bfc0cf178dc21b0fe33e0ce3b90a18858abaf1b):
```
{
status: "ready",
sha1: "9bfc0cf178dc21b0fe33e0ce3b90a18858abaf1b",
extra: {
build_url: "https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge/493/",
root_build_cause: "MANUALTRIGGER",
version: "10.2.2-508-g9bfc0cf",
node_name: "158.69.91.83+xenial_trusty_pbuilder_huge__8d10ffc3-3484-40d4-bbad-db68c6eb8dc7",
job_name: "ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge",
package_manager_version: "10.2.2-508-g9bfc0cf-1xenial"
},
url: "https://1.chacra.ceph.com/r/ceph/jewel/9bfc0cf178dc21b0fe33e0ce3b90a18858abaf1b/ubuntu/xenial/flavors/default/",
distro_codename: "xenial",
modified: "2016-09-12 18:11:50.242532",
distro_version: "16.04",
project: "ceph",
flavor: "default",
ref: "jewel",
chacra_url: "https://1.chacra.ceph.com/repos/ceph/jewel/9bfc0cf178dc21b0fe33e0ce3b90a18858abaf1b/ubuntu/xenial/flavors/default/",
archs: [
"x86_64"
],
distro: "ubuntu"
},
```

**Comment by andrewschoen** [comment]
@zmc Those repos disappeared on you because the hard drives of both chacra1 and chacra2 filled up because of a bug related to chacra not deleting repo paths. @alfredodeza had to do some emergency cleanup and those must have been removed.

Sorry to pull the rug out from under you here. I'll see if can force an update somehow to change the status of these in shaman.

**Comment by zmc** [comment]
More tests:
* [``teuthology-suite -v -c master -s upgrade/jewel-x -m vps -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com --filter-out 14.04 $PWD/shaman.yaml``](http://pulpito.ceph.com/zack-2016-09-14_15:30:05-upgrade:jewel-x-master-distro-basic-vps/)
* [``teuthology-suite -v -c master -s upgrade/jewel-x -m vps -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com --filter-out 14.04``](http://pulpito.ceph.com/zack-2016-09-14_15:23:18-upgrade:jewel-x-master-distro-basic-vps/)

**Comment by andrewschoen** [comment]
I was expecting some work in teuthology.suite to find out what sha1 to test based on what distros are being used in the job, perhaps using the ``sha1=latest`` feature of shaman. Is that work we plan to do later? Or maybe we don't even want to do that anymore?

I did see a few references to ``GitbuilderProject`` in ``teuthology.suite.util`` still, for example: https://github.com/ceph/teuthology/blob/master/teuthology/suite/util.py#L102

**Comment by zmc** [comment]
@andrewschoen This PR is focusing on supporting the new build system as a drop-in replacement to the old. The "latest for all distros" feature idea isn't fully fleshed out so work hasn't started on it.

Your link is to the master branch :)

**Comment by andrewschoen** [comment]
@zmc ah, gotcha. I just wanted to make sure we were still thinking about the "latest for all distros" feature.

**Comment by zmc** [comment]
An update: I've been sidetracked a bit lately but picked this back up today. I discovered an issue while running upgrade tests where ``ShamanProject`` wasn't using the same rules for ref precedence as ``GitbuilderProject``. It took a bit of refactoring to get them to share the same rules, but I did find and fix a couple long-standing, apparently unnoticed bugs in the process. So, more tests:
* [``teuthology-suite -v -c master -s upgrade/jewel-x -m vps -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com $PWD/shaman.yaml``](http://pulpito.ceph.com/zack-2016-09-21_17:46:31-upgrade:jewel-x-master-distro-basic-vps/)
* [``teuthology-suite -v -c master -s upgrade/jewel-x -m vps -p 1 -t wip-shaman-2 -k distro -e zack@redhat.com``](http://pulpito.ceph.com/zack-2016-09-21_17:47:10-upgrade:jewel-x-master-distro-basic-vps/)

**Comment by dmick** [comment]
"precendence" on the commit msg in 35e1d7f

**Comment by dmick** [comment]
So far this all looks credible to me.

**Pull request merged**
