### PR TITLE
requirements: bump ansible

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
the deployment test will not pass because with that config the worker is trying to checkout and bootstrap master branch, which is currently cannot happen because of issue with LC_ALL=C:
```
  File "/home/worker/src/teuthology_master/virtualenv/bin/teuthology-worker", line 33, in <module>
    sys.exit(load_entry_point('teuthology', 'console_scripts', 'teuthology-worker')())
  File "/home/worker/src/teuthology_master/scripts/worker.py", line 7, in main
    teuthology.worker.main(parse_args())
  File "/home/worker/src/teuthology_master/teuthology/worker.py", line 82, in main
    fetch_teuthology('master')
  File "/home/worker/src/teuthology_master/teuthology/repo_utils.py", line 415, in fetch_teuthology
    return fetch_repo(url, branch, commit, bootstrap_teuthology, lock)
  File "/home/worker/src/teuthology_master/teuthology/repo_utils.py", line 339, in fetch_repo
    while proceed():
  File "/home/worker/src/teuthology_master/teuthology/contextutil.py", line 133, in __call__
    raise MaxWhileTries(error_msg)
teuthology.exceptions.MaxWhileTries: reached maximum tries (60) after waiting for 600 seconds

```

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
