### PR TITLE
Remove old kernels on RPM-based systems

### PR DESCRIPTION
**Pull request by zmc**
http://tracker.ceph.com/issues/11627

### CODE REVIEW

**Comment by ktdreyer** [comment]
yum is supposed to automatically remove old kernels and only keep the last three around (see `installonlypkgs` and `installonly_limit` in `yum.conf(5)` ). Are we using yum to install kernels?

**Comment by zmc** [comment]
``installonly_limit`` is set, but I don't see ``installonlypkgs``

**Comment by ktdreyer** [comment]
when `installonlypkgs` is unset, yum uses the default value specified in the yum.conf manpage (`kernel, kernel-bigmem, kernel-enter‐prise,  kernel-smp,  kernel-debug,  kernel-unsupported,  kernel-source, kernel-devel, kernel-PAE, kernel-PAE-debug`)

In other words it should be doing the right thing. I wonder what the kernel task is doing, though.

**Comment by zmc** [comment]
The kernel task is using yum. I'm not sure why kernels are accumulating, but they clearly are...

**Comment by ktdreyer** [comment]
(discussed in IRC, the problem is likely to be at https://github.com/ceph/teuthology/blob/master/teuthology/task/kernel.py#L414-L423)

```
            proc = role_remote.run(
                args=[
                    'sudo',
                    'rpm',
                    '-ivh',
                    '--oldpackage',
                    '--replacefiles',
                    '--replacepkgs',
                    remote_pkg_path(role_remote),
                ])
```

**Pull request merged**
