### PR TITLE
Add the option to enable or disable epel during install or upgrade

### PR DESCRIPTION
**Pull request by vasukulkarni**
Option to enable_epel during install task to resolve package dependency
using epel repo

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
Months ago, @andrewschoen made this possible using ansible. Why not use that?

**Comment by andrewschoen** [comment]
@vasukulkarni Yeah, I'd say using the downstream setup playbook here is the right method. Unless you're having some troubles with it I'm not aware of?

**Comment by vasukulkarni** [comment]
@zmc @andrewschoen This is for different issue, downstream.yml is already being used for a very long time, we have issues running in magna lab on rhel due to some package dependency for firefly, hammer or master branch, check 13203 where we ended up adding fcgi to ansible. With enable_epel override the runs will be clean

**Comment by zmc** [comment]
This is what I was talking about earlier:
https://github.com/ceph/ceph-cm-ansible/blob/master/roles/common/tasks/epel.yml

**Comment by vasukulkarni** [comment]
I this this is not required for now, would submit a pr for ansible to install some dependent packages.

**Pull request closed without merging**
