### PR TITLE
Update distro maps

### PR DESCRIPTION
**Pull request by djgalloway**
- Ubuntu (20.04) Focal should be the default now.  It's the latest and we target it for octopus, pacific, and master.
- RHEL and CentOS 8.4 have been available for weeks
- In the process of adding support for CentOS 9 Stream.  May as well add it here now.

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by yuriw** [comment]
can we wait to merge it then for a week or so, until the final nautilus release is tested and published ?

**Review by batrick — APPROVED** [review]

**Review by idryomov — APPROVED** [review]

**Comment by kshtsk** [comment]
@susebot run deploy

**Review by kshtsk — CHANGES_REQUESTED** [review]
the unit tests should fixed before merging

**Comment by kshtsk** [comment]
any updates?

**Comment by djgalloway** [comment]
jenkins test

**Comment by kshtsk** [comment]
```
_________________ TestShamanProject.test_get_distro_config[16] _________________

self = <teuthology.test.test_packaging.TestShamanProject object at 0xffff8d558130>
matrix_index = 16

    @pytest.mark.parametrize(
        "matrix_index",
        range(len(DISTRO_MATRIX) + len(DISTRO_MATRIX_NOVER)),
    )
    def test_get_distro_config(self, matrix_index):
        (distro, version, codename, expected) = \
            (self.DISTRO_MATRIX + self.DISTRO_MATRIX_NOVER)[matrix_index]
        config = dict(
            os_type=distro,
            os_version=version
        )
        gp = self.klass("ceph", config)
>       assert gp.distro == expected
E       AssertionError: assert 'ubuntu/20.04' == 'ubuntu/18.04'
E         - ubuntu/20.04
E         ?        ^^
E         + ubuntu/18.04
E         ?        ^^

teuthology/test/test_packaging.py:497: AssertionError
```

**Review by kshtsk — APPROVED** [review]
lgtm

**Pull request merged**
