### PR TITLE
Changes for bootstrap to work on RHEL

### PR DESCRIPTION
**Pull request by vasukulkarni**
Changes for Redhat Linux
http://fpaste.org/348380/36955145/raw/

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
"redhat linux" - do you mean "Red Hat Enterprise Linux"/"RHEL" ? ;)

**Comment by vasukulkarni** [comment]
@zmc just added the enterprise server as well, they all same flavors and the commit now says RHEL :)

**Comment by zmc** [comment]
@vasukulkarni did you check that the package name change is needed for / won't break fedora?

**Comment by vasukulkarni** [comment]
@zmc  this will not break fedora, https://paste.fedoraproject.org/357536/1625146/raw/

**Comment by dmick** [comment]
So this does two separate things:

1) changes from community-mysql-devel to mysql-community-devel
2) adds a new openssl-devel

What's the reason for each change?   

1) community-mysql-devel still appears to exist in Fedora:  https://apps.fedoraproject.org/packages/community-mysql-devel ; however, mysql-community-devel  does not:  https://apps.fedoraproject.org/packages/s/mysql-community-devel

2) what adds the new dependency on openssl-devel?

**Comment by vasukulkarni** [comment]
@dmick 
1) I am using the *official* rpm's which has clear documentation for all distro's(rhel/fedora/centos) and how to install those packages: http://dev.mysql.com/doc/refman/5.7/en/linux-installation-rpm.html
2) This is not a *new* dependency that is needed, The old bootstrap just assumes that package is installed which is can be false for fedora/rhel and the bootstrap can fail.

**Comment by zmc** [comment]
@vasukulkarni I'm not sure I understand fully. You claim this PR won't break Fedora, but your paste shows the package being installed from an external repository.

Is this correct: You want teuthology's bootstrap to attempt to install ``mysql-community-devel  ``, which doesn't exist on Fedora, instead of ``community-mysql-devel``, which does? 

Won't that make bootstrap fail on stock Fedora?

**Comment by vasukulkarni** [comment]
@zmc updated, and fedora is untoched in this pr, so it should be like before.

**Comment by dmick** [comment]
So, MySQL support in RHEL appears to be based on the MariaDB fork.  Both user and devel packages are available.  It seems clear to me that we should base teuthology support on bundled packages.

I'll file a followup.

**Pull request merged**
