### PR TITLE
task/install/redhat: Removing packages based on OS in cleanup task

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
script modified to remove packages  based on OS in the cleanup task.While uninstalling packages, both rpm and deb packages are getting first and  in the next step checking the OS name and removing the packages.

As part of fix first checking the OS name after that getting the appropriate packages to remove.

### CODE REVIEW

**Comment by kshtsk** [comment]
I wonder, does RedHat support deb packages?

**Comment by SrinivasaBharath** [comment]
Teuthology Log-   http://pulpito.ceph.redhat.com/skanta-2021-01-12_07:32:23-rados:singleton-master-distro-basic-clara/

**Comment by rakeshgm** [comment]
We support for some of the older versions

**Comment by SrinivasaBharath** [comment]
Currently we are supporting the deb packages.

**Comment by SrinivasaBharath** [comment]
To clean up the branch and to raise the PR  only with required changes.

**Pull request closed without merging**
