### PR TITLE
fix a --subset bug that misses facets in some cases

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@zmc this is rebased and tox -e flake8 has no issue. The tostr() helper is added to support __str__() because it is implemented recursively with an additional depth argument to please the eye.

Note that I also include a workaround for a pip 8.0.0 bug preventing bootstrap to work, so that automated checks work. It showed up yesterday and I'm not sure what's the proper way to deal with it.

**Comment by dachary** [comment]
@zmc ping ?

**Comment by zmc** [comment]
@dachary hmm, I'd added a comment or two in the other PR before it was closed and now I can't find it. I remember that one of my issues was the strange ``tostr()`` methods - why not use ``__str__()`` since it's a standard?

**Comment by zmc** [comment]
Also, the bootstrap fix shouldn't be in here - it should be in a separate PR (I'm attempting to fix that and similar issues in #775)

**Comment by dachary** [comment]
@zmc The tostr() helper is added to support str() because it is implemented recursively with an additional depth argument to please the eye.

**Comment by dachary** [comment]
@zmc I removed the extra pip 8 related bug fix.

**Comment by zmc** [comment]
@dachary hrm, ok. Could you rebase this on master so unit tests can execute properly?

**Comment by dachary** [comment]
@zmc rebased & repushed !

**Comment by dachary** [comment]
@zmc fixed the failed test (because a prototype of the test helper changed in december). Should be good now !

**Pull request merged**
