### PR TITLE
modify initial of help in teuthology of explain function

### PR DESCRIPTION
**Pull request by yonghengdexin735**
I run the help for teuthology(like: teuthology-lock -h), the arguments for helps of explain function didn't distinguish between upper case and lower case in the first letter.

Signed-off-by: zhang.zezhu <zhang.zezhu@zte.com.cn>

### CODE REVIEW

**Comment by zmc** [comment]
@yonghengdexin735, why not use ``--owner`` ?

**Comment by yonghengdexin735** [comment]
@zmc , this view is another pull request for modify initial of help in teuthology of explain function, I think this modify can optimize our help of teuthology. 
Thanks.

**Comment by yonghengdexin735** [comment]
@zmc , would you please review for me, thanks!

**Comment by dmick** [comment]
I don't see how this helps anything at all, and it just seems like pointless churn.  Why does it matter whether the first character of the help string is capitalized?

**Comment by yonghengdexin735** [comment]
@dmick ,because I find the first character of the help string some times for upper or lower, I think the unification is better.

**Comment by dmick** [comment]
Yeah, that's not worth it to me, but I've said my opinion.

**Comment by zmc** [comment]
I agree with @dmick that this seems unnecessary. It also introduces typos.

**Pull request closed without merging**
