### PR TITLE
remove circular imports

### PR DESCRIPTION
**Pull request by kshtsk**
Fixes: https://tracker.ceph.com/issues/42871

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by vasukulkarni** [comment]
@kshtsk can you also add tracker for the issue or improvement? Thanks!

**Comment by kshtsk** [comment]
https://tracker.ceph.com/issues/42871

**Comment by vasukulkarni** [comment]
LGTM, it should go through rados or fs subset testing as it touches the core for every tests.

**Comment by kshtsk** [comment]
> @kshtsk can you also add tracker for the issue or improvement? Thanks!

@vasukulkarni what exactly you meant, like add 'Fixes: ' to the description or to each commit in the PR?

**Comment by vasukulkarni** [comment]
@kshtsk I meant in the description in the first box(which I edited now), This will help understand fixes/enhancement better.

**Comment by vasukulkarni** [comment]
I think we should also start running smaller test suites in sepia just to ensure there is no regression for core components.

**Comment by kshtsk** [comment]
@vasukulkarni like this? 
```
teuthology-suite  -c luminous -s ceph-ansible --ceph-repo http://github.com/ceph/ceph --suite-repo https://github.com/ceph/ceph --suite-branch luminous --suite-relpath qa -m mira -t refs/pull/1361/merge
```

**Comment by vasukulkarni** [comment]
@kshtsk yeah, instead of ceph-ansible, we can run smoke and either use nautilus or luminous branch

```
teuthology-suite  -c luminous (or nautilus) -s smoke --ceph-repo http://github.com/ceph/ceph --suite-repo https://github.com/ceph/ceph --suite-branch luminous (or nautilus) --suite-relpath qa -m mira -t refs/pull/1361/merge
```

**Comment by kshtsk** [comment]
http://pulpito.ceph.com/kyr-2019-11-22_08:34:46-smoke-luminous-distro-basic-mira/

**Comment by kshtsk** [comment]
http://pulpito.ceph.com/kyr-2019-11-22_08:58:57-smoke-nautilus-distro-basic-ovh/

**Comment by vasukulkarni** [comment]
Is it checking out the ref branch? I am not seeing in the teuthology log, maybe its in worker log?

**Comment by kshtsk** [comment]
> Is it checking out the ref branch? I am not seeing in the teuthology log, maybe its in worker log?

yes:
```
2019-11-22T16:58:39.908 INFO:teuthology.repo_utils:Fetching refs/pull/1361/merge from origin
2019-11-22T16:58:40.026 INFO:teuthology.repo_utils:Resetting repo at /home/teuthworker/src/git.ceph.com_git_teuthology_PR#1361 to branch origin/pull/1361/merge
2019-11-22T16:58:40.057 INFO:teuthology.repo_utils:Skipping bootstrap as it was already done in the last 60s
2019-11-22T16:58:40.133 INFO:teuthology.repo_utils:Fetching nautilus from origin
2019-11-22T16:58:44.434 INFO:teuthology.repo_utils:Resetting repo at /home/teuthworker/src/github.com_ceph_ceph_nautilus to branch origin/nautilus
2019-11-22T16:58:45.587 INFO:teuthology.worker:Creating archive dir /home/teuthworker/archive/kyr-2019-11-22_08:58:57-smoke-nautilus-distro-basic-ovh/4533735
2019-11-22T16:58:45.588 INFO:teuthology.worker:Running job 4533735
```
(from: http://qa-proxy.ceph.com/teuthology/kyr-2019-11-22_08:58:57-smoke-nautilus-distro-basic-ovh/4533735/worker.log)

**Comment by kshtsk** [comment]
@vasukulkarni interesting observation, that teuthology log can show different sha1 version for refs/pull/X/merge branches if you run several runs in parallel and someone merge a PR to master in the middle. The github automatically merges the refs/pull/X/head again if there is no merge conflicts. So the running test agains refs/pull/X/head may seem more reliable in some circumstances.

**Comment by kshtsk** [comment]
Is this failure known to you?
http://qa-proxy.ceph.com/teuthology/kyr-2019-11-22_08:34:46-smoke-luminous-distro-basic-mira/4533594/teuthology.log

**Comment by kshtsk** [comment]
@vasukulkarni 
```
2019-11-22T16:55:02.503 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_PR#1361/teuthology/contextutil.py", line 32, in nested
    vars.append(enter())
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/teuthworker/src/github.com_ceph_ceph_luminous/qa/tasks/ceph_deploy.py", line 677, in cli_test
    execute_cdeploy(admin, zap_disk, path)
  File "/home/teuthworker/src/github.com_ceph_ceph_luminous/qa/tasks/ceph_deploy.py", line 612, in execute_cdeploy
    "failed during ceph-deploy cmd: {cmd} , ec={ec}".format(cmd=cmd, ec=ec))
RuntimeError: failed during ceph-deploy cmd: disk zap mira061:/dev/sdb , ec=1
```

**Comment by kshtsk** [comment]
looks like it is https://tracker.ceph.com/issues/22463 however I'm not sure

**Comment by vasukulkarni** [comment]
> @vasukulkarni
> 
> ```
> 2019-11-22T16:55:02.503 ERROR:teuthology.contextutil:Saw exception from nested tasks
> Traceback (most recent call last):
>   File "/home/teuthworker/src/git.ceph.com_git_teuthology_PR#1361/teuthology/contextutil.py", line 32, in nested
>     vars.append(enter())
>   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
>     return self.gen.next()
>   File "/home/teuthworker/src/github.com_ceph_ceph_luminous/qa/tasks/ceph_deploy.py", line 677, in cli_test
>     execute_cdeploy(admin, zap_disk, path)
>   File "/home/teuthworker/src/github.com_ceph_ceph_luminous/qa/tasks/ceph_deploy.py", line 612, in execute_cdeploy
>     "failed during ceph-deploy cmd: {cmd} , ec={ec}".format(cmd=cmd, ec=ec))
> RuntimeError: failed during ceph-deploy cmd: disk zap mira061:/dev/sdb , ec=1
> ```

It is a test issue, @yuriw can you remove this test from smoke? I guess its outdated and ceph-deploy suite is sufficient for old branches.

**Pull request merged**
