### PR TITLE
eliminating kernel task duplication

### PR DESCRIPTION
**Pull request by sunilkumarn417**
- code changes to avoid multiple kernel task entries in tasks list.

Signed-off-by: sunilkumarn417 <sunnagar@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
okay to test

**Comment by kshtsk** [comment]
ok to test

**Comment by vasukulkarni** [comment]
@sunilkumarn417 can you add one of the test link from octo lab?

**Comment by sunilkumarn417** [comment]
> @sunilkumarn417 can you add one of the test link from octo lab?

@vasukulkarni tried scheduling test suite with PR changes, but there was some issue. Executed this locally and logs are stored at `magna002:/home/sunnagar/teuth/test_kernel_patch-10-06-20-1591765428/teuthology.log`

**Comment by kshtsk** [comment]
@susebot run deploy

**Pull request merged**
