### PR TITLE
Wip subset fix

### PR DESCRIPTION
**Pull request by athanatos**

### CODE REVIEW

**Comment by dachary** [comment]
@athanatos reviewed it and tested it manually for a week and found no issue. Assigning to @zmc because I don't feel confortable doing the merge myself.

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by dachary** [comment]
@zmc  in a nutshell this fix is important otherwise --subset will sometime miss a workload. That does not happen when scheduling the larger suites. Rather when scheduling a part of a suite that triggers the bug. This is specially important when validating the pull requests with a few jobs because it creates a confusion when a job turns out to fail while the reviewer was convinced it was run when testing the pull request.

**Comment by dachary** [comment]
@zmc this is a very important pull request. Without it we will miss tests. Thanks :-)

**Comment by zmc** [comment]
@dachary apologies for not getting to this sooner!

* It would be really nice if it passed ``flake8``.
* Why not defined ``__str__()`` instead of the magic ``tostr()`` method?

**Comment by dachary** [comment]
@zmc will re-submit with the requested changes

**Pull request closed without merging**
