### PR TITLE
task/ceph-ansible: copy purge-cluster to top-level directory for it to work

### PR DESCRIPTION
**Pull request by vasukulkarni**
set ANSIBLE_LIBRARY environment variable for purge cluster playbook to work properly.

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@andrewschoen @leseb suggested either to set the env or move the purge-cluster.yml one level above, I find this more better.

**Comment by vasukulkarni** [comment]
Doesn't like inside venv 'ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT''

http://qa-proxy.ceph.com/teuthology/vasu-2017-09-19_23:53:18-ceph-ansible-master-distro-basic-ovh/1650200/teuthology.log

**Comment by andrewschoen** [comment]
@vasukulkarni If this works I guess it's fine, but my contention is that our CI does not test this method nor do our docs mention it. They both take the approach of moving the playbook up one level.

**Comment by vasukulkarni** [comment]
@andrewschoen anyway that didn't work on Ubuntu,  I think I will just move the playbook one folder up.

**Comment by vasukulkarni** [comment]
@andrewschoen done!

**Pull request merged**
