### PR TITLE
Make the number machines to be reserved configurable

### PR DESCRIPTION
**Pull request by zhouyuan**
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
ok to test

**Comment by zmc** [comment]
I like the idea here. A few small things, though. 

One is that the name isn't specific enough; ``min_to_reserve`` -> min of what? Maybe ``reserve_machines`` or similar would be better.

Another is that, if this were set to a negative number, weird things would happen. There should be some sanity checking, and a value of ``0`` should disable the feature entirely.

Finally, please include some brief documentation in [siteconfig.rst](https://github.com/ceph/teuthology/blob/master/docs/siteconfig.rst).

Thanks!

**Comment by zhouyuan** [comment]
@zmc any comments on the new version?

**Comment by zmc** [comment]
@zhouyuan ah, didn't see the update. This looks great, thanks for making those changes!

**Pull request merged**
