### PR TITLE
openstack: use ssh identity as key_filename by default

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@zmc @gregsfortytwo what's next, I don't understand how much time will it take for the 'default' check to be updated it is already several days 'Waiting for status to be reported'.

**Comment by vasukulkarni** [comment]
jenkins test this please

**Comment by vasukulkarni** [comment]
jenkins retest this please

**Comment by gregsfortytwo** [comment]
That behavior is odd, I see the other jobs in https://jenkins.ceph.com/job/teuthology-pull-requests/ but not for this PR?

jenkins retest this please

**Comment by kshtsk** [comment]
jenkins retest this please

**Comment by kshtsk** [comment]
@gregsfortytwo Is this because I'm not allowed to create branches in this repo?

**Comment by kshtsk** [comment]
@gregsfortytwo Or I'm trying to go with PR from not allowed branches?

**Comment by zmc** [comment]
test this please

**Pull request merged**
