### PR TITLE
ceph_ansible: make code py3 compatible

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by vasukulkarni** [comment]
LGTM, Thanks!

**Comment by vasukulkarni** [comment]
@rakeshgm can you run tests in octo lab?

**Comment by kshtsk** [comment]
@vasukulkarni @rakeshgm do you have any updates? can we merge this already?

**Comment by rakeshgm** [comment]
@kshtsk LGTM, I think the compatibility for python3 looks good. As for the script execution, we can check once we start testing. but I am okay with the merge.

**Comment by vasukulkarni** [comment]
If the branch is in teuthology, I could have run following cmd on sepia:

```
 teuthology-suite  -c luminous -s ceph-ansible --ceph-repo http://github.com/ceph/ceph --suite-repo https://github.com/ceph/ceph --suite-branch luminous --suite-relpath qa  --dry-run -m mira -t wip-py3-ceph-ansible
```

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2019-11-20_19:55:04-ceph-ansible-luminous-distro-basic-mira/ , worse case if a test fails one of us can add a fix.

**Comment by kshtsk** [comment]
> If the branch is in teuthology, I could have run following cmd on sepia:
> 
> ```
>  teuthology-suite  -c luminous -s ceph-ansible --ceph-repo http://github.com/ceph/ceph --suite-repo https://github.com/ceph/ceph --suite-branch luminous --suite-relpath qa -m mira -t wip-py3-ceph-ansible
> ```

JFYI, it was not in teuthology, but now you can try and use new feature: -t refs/pull/1360/merge and it grabs the code from the PR 1360 merged against master

**Pull request merged**
