### PR TITLE
Add GitHub Actions definition for CI

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by zmc** [comment]
Second commit takes CI time down from 29m to 4m.

**Review by kshtsk — APPROVED** [review]
Looks great, however, do we really need to run tests on push?

**Comment by zmc** [comment]
Unit tests? I'd argue yes - we have decent unit test coverage and can prevent regressions this way

**Comment by kshtsk** [comment]
> Unit tests? I'd argue yes - we have decent unit test coverage and can prevent regressions this way

No, I mean, these checks will run for PR, and later when they merged to master (on push). I was asking if want this, I don't object, just asking

**Comment by zmc** [comment]
Oh! I just misunderstood. I agree, we don't need to run tests on push. I'll remove that. Thanks!

**Review by kshtsk — APPROVED** [review]

**Pull request merged**
