### PR TITLE
hadoop: support rhel and ubuntu

### PR DESCRIPTION
**Pull request by noahdesu**
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
...it looks like this ran through the testing despite the query? At least, looking at the Travis CI.

**Comment by gregsfortytwo** [comment]
okay to test

**Comment by alfredodeza** [comment]
OK to test

**Comment by alfredodeza** [comment]
ok to test

**Comment by noahdesu** [comment]
lint failed the first time and I pushed a fixed on top. maybe that force
push confused things?

**Comment by andrewschoen** [comment]
@noahdesu It's ok, we were just testing out some config for travis ci - it's nothing you did.

Thanks!

**Pull request merged**
