### PR TITLE
Fix dependency handling and unit tests

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
From Jenkins:
```
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from teuthology==0.1.0->-r requirements.txt (line 2))
```

**Comment by zmc** [comment]
This should obsolete #568

**Comment by ktdreyer** [comment]
Nice!

**Comment by ivotron** [comment]
cool!

**Pull request merged**
