### PR TITLE
suite/util: add opensuse to distro defaults

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@vasukulkarni do you have an idea why this is failing https://ceph-ci.suse.de/job/teuthology-deploy-ovh/54/artifact/logs/run/teuthology-job-2.html on some mirroring?

**Comment by vasukulkarni** [comment]
Its failing for ceph-radosgw but I do see the package, https://4.chacra.ceph.com/r/ceph/nautilus/e3616adab9649a893d8fa227c78bd080d16949b6/centos/7/flavors/default/x86_64/

Command failed on target-pr-1373-050 with status 1: 'sudo yum -y install ceph-radosgw'

**Comment by vasukulkarni** [comment]
Sorry ignore the previous mesg, I think its some mirror sites are broken, either its intermittent or we have to stop the vm and run 'yum update meta' to figure out which mirror is that.

**Pull request merged**
