### PR TITLE
Drop MySQL dependency

### PR DESCRIPTION
**Pull request by zmc**
I think it's been years since anything in the project used the
mysqlclient package, so let's stop making everyone install it and everything it requires.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
I'm actually not confident teuthology-coverage is and who is using, I'm happy to merge it as soon as conflicts resolved. Just curious, should cleanup teuthology code base from any notice of teuthology-coverage now? If so does it make sense that changes to accompany this PR?

**Comment by tchaikov** [comment]
@kshtsk teuthology-coverage was removed by #1419.

**Comment by kshtsk** [comment]
> @kshtsk teuthology-coverage was removed by #1419.

not everything:
```
$ grep -r coverage teuthology
teuthology/misc.py:        'ceph-coverage',
teuthology/misc.py:        '{tdir}/archive/coverage'.format(tdir=testdir),
teuthology/misc.py:            'ceph-coverage',
teuthology/misc.py:            '{tdir}/archive/coverage'.format(tdir=testdir)]
teuthology/misc.py:                    'ceph-coverage',
teuthology/misc.py:                    '{tdir}/archive/coverage'.format(tdir=testdir),
teuthology/results.py:        generate_coverage(archive_dir, name)
teuthology/results.py:def generate_coverage(archive_dir, name):
teuthology/results.py:    coverage_config_keys = ('coverage_output_dir', 'coverage_html_dir',
teuthology/results.py:                            'coverage_tools_dir')
teuthology/results.py:    for key in coverage_config_keys:
teuthology/results.py:                "'%s' not in teuthology config; skipping coverage report",
teuthology/results.py:    log.info('starting coverage generation')
teuthology/results.py:            os.path.join(os.path.dirname(sys.argv[0]), 'teuthology-coverage'),
teuthology/results.py:            os.path.join(config.coverage_output_dir, name),
teuthology/results.py:            os.path.join(config.coverage_html_dir, name),
teuthology/results.py:            config.coverage_tools_dir,
teuthology/task/install/util.py:            if config.get('coverage'):
teuthology/task/lockfile.py:                'ceph-coverage',
teuthology/task/lockfile.py:                '{tdir}/archive/coverage'.format(tdir=testdir),
```

**Comment by kshtsk** [comment]
btw, does that `ceph-coverage` relate to _teuthology-coverage_ somehow?

**Comment by toabctl** [comment]
needs a rebase

**Comment by tchaikov** [comment]
> btw, does that `ceph-coverage` relate to _teuthology-coverage_ somehow?

guess you are questioning yourself =)

but let me join your discussion: https://github.com/ceph/ceph/blob/master/src/ceph-coverage.in

**Comment by kshtsk** [comment]
there is still `generate_coverage` in teuthology-results

**Comment by zmc** [comment]
Rebased. I think that removing the remaining references to teuthology-coverage would be good and I'm happy to do it here if folks agree, or it could be a follow-up.

**Comment by kshtsk** [comment]
I'm fine with the cleanup as separate commit within this PR, as well as followup.

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
http://pulpito.ceph.com/kyr-2020-05-28_19:00:48-dummy-master-distro-basic-ovh/

**Pull request merged**
