### PR TITLE
suite: take shorthand repo, user/repo for --suite-repo and --ceph-repo args

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
This doesn't seem to work:
```
>>> suite.expand_short_repo_name('ceph', 'git://git.ceph.com/ceph.git')
['git:', '', 'git.ceph.com', 'ceph']
>>> suite.expand_short_repo_name('ceph', 'https://github.com/ceph/ceph')
['https:', '', 'github.com', 'ceph', 'ceph']
>>> suite.expand_short_repo_name('ceph', 'https://github.com/ceph/ceph/')
['https:', '', 'github.com', 'ceph', 'ceph', 'ceph']
```

It should probably have unit tests :)

**Comment by liewegas** [comment]
works for me!  e.g.,

teuthology-suite -s rados --filter upgrade --subset 1/100 -c master -n 5 --ceph-repo ceph  --suite-repo liewegas/ceph -p 50 --suite-branch wip-backoff --dry-run

**Comment by jcsp** [comment]
Working for me!

**Comment by jcsp** [comment]
Why do we care about trailing slashes in particular?

**Comment by smithfarm** [comment]
@zmc Seems to me that stripping off the trailing slash is not necessarily wrong. It's sanitizing the user input.

Instead of sanitizing to `https://github.com/ceph/ceph` (without trailing slash), would it make sense to go all the way to (what I consider to be) canonical format, i.e. `https://github.com/ceph/ceph.git` ?

**Comment by smithfarm** [comment]
@liewegas I took the liberty of pushing a commit into this PR - hope that's OK!

@zmc The commit addresses the trailing slash issue you found and adds a few more unit tests.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Pull request merged**
