### PR TITLE
use libcloud 2.8.0 version 

### PR DESCRIPTION
**Pull request by gekios**
Suggesting using 2.8.0 version of apache-libcloud that introduces
a fix on openstack driver.
(https://github.com/apache/libcloud/pull/1367 is fixing issue
https://github.com/apache/libcloud/issues/1365)

Signed-off-by: Georgios Kyratsas <gkyratsas@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
ok to test

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
> * latest ist 2.8.0 (not 2.7.0)
it's better to avoid such words like 'latest' :-D

**Comment by gekios** [comment]
Oh my bad, I removed it from the PR message but missed it on the commit one.

**Comment by toabctl** [comment]
Any reason why we don't want to use 2.8.0 ?

**Comment by gekios** [comment]
The only reason is that I have tested it in 2.7.0 so I know that it works and didn't find any issues.

**Comment by kshtsk** [comment]
integration tests are still failing in jenkins :-(

**Comment by kshtsk** [comment]
@gekios any further work on this PR?

**Comment by toabctl** [comment]
@gekios can we update to 2.8.0 please? That seems to be just a bug fix release. See http://libcloud.apache.org/blog/2020/01/02/libcloud-2-8-0-released.html

**Comment by gekios** [comment]
OK I tried 2.8.0 as @toabctl and it passed :)

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@toabctl are your comments addressed?

**Comment by kshtsk** [comment]
retest this please

**Pull request merged**
