### PR TITLE
run: drop StringIO usage for py3 compatibility

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by toabctl** [comment]
@kshtsk there is `StringIO` in python3. Maybe it would be simpler to just use https://six.readthedocs.io/#six.StringIO to keep the change minimal so this can get merged quicker?

**Comment by kshtsk** [comment]
> @kshtsk there is `StringIO` in python3. Maybe it would be simpler to just use https://six.readthedocs.io/#six.StringIO to keep the change minimal so this can get merged quicker?

no, because for most cases there is cStringIO used in teuthology which different to StringIO

**Comment by vasukulkarni** [comment]
@rakeshgm @yuriw I think we could start using this branches to run partial rados suite  + smoke and get them merged soon

**Comment by kshtsk** [comment]
@vasukulkarni do we have some small test case to test this PR with 'email-on-error' feature?

**Comment by vasukulkarni** [comment]
> @vasukulkarni do we have some small test case to test this PR with 'email-on-error' feature?

I dont think so , @zmc do you know of any? I think email-on-error might be too much considering how many tests one suite has.

**Comment by vasukulkarni** [comment]
Here we could just run one subset of rados to ensure its good for merge and go ahead with that.

**Pull request merged**
