### PR TITLE
platform.linux_distribution() is deprecated; stop using it

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/18141
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@zmc Ping

**Comment by smithfarm** [comment]
platform.linux_distribution() is deprecated since python 3.5, and will be removed in python 3.7 (see https://docs.python.org/3.6/library/platform.html#platform.linux_distribution).

**Comment by smithfarm** [comment]
The implementation in Python 2.7 returns `(,,)` on newer distros like openSUSE Tumbleweed (which dropped the old `/etc/SuSE-release` now that `/etc/os-release` is the new standard). I think this `(,,)` return value happens in newer Fedoras as well, but I haven't tried it.

**Comment by smithfarm** [comment]
@zmc When you say "all OSes" which OSes do you mean? Are there any that don't have `/etc/os-release` ?

**Comment by ktdreyer** [comment]
FYI [mock](https://github.com/rpm-software-management/mock) recently switched to the [distro](https://github.com/nir0s/distro) lib, now that `platform.dist` and `platform.linux_distribution` are going away in py37.

**Comment by smithfarm** [comment]
@ktdreyer Do we need an elaborate python module when a glance at `/etc/os-release` gives us the information we need?

**Comment by ktdreyer** [comment]
Teuthology does a lot already - it was just a suggestion :)

**Comment by smithfarm** [comment]
In https://github.com/ceph/ceph/pull/23111 I have unit tests that cover "all" OSes. I will add a commit to this PR implementing these unit tests in teuthology so we can be confident that `platform.linux_distribution` is no longer needed.

**Comment by smithfarm** [comment]
Added unit tests and support for new distros. Pinging again for review.

**Comment by smithfarm** [comment]
@zmc Ping

**Pull request merged**
