### PR TITLE
docs: improve instructions for installing teuthology

### PR DESCRIPTION
**Pull request by ljflores**
This only applies to the "Ubuntu, Fedora, & Suse/Opensuse" section.

Signed-off-by: Laura Flores <lflores@redhat.com>

### CODE REVIEW

**Review by kamoltat — APPROVED** [review]
LGTM

**Comment by amathuria** [comment]
Looks good @ljflores!

**Review by amathuria — APPROVED** [review]
Looks good @ljflores!

**Comment by ljflores** [comment]
@neha-ojha this could probably be merged if it looks okay to you

**Review by neha-ojha — APPROVED** [review]
https://ceph--1691.org.readthedocs.build/projects/teuthology/en/1691/INSTALL.html

**Pull request merged**
