### PR TITLE
py2 backports: 2020-05-19

### PR DESCRIPTION
**Pull request by kshtsk**
Cherry-picks from master.

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by tchaikov** [comment]
can i trade the review of https://github.com/ceph/teuthology/pull/1474 with this one?

**Comment by kshtsk** [comment]
> can i trade the review of #1474 with this one?

oh... seems like you've merged it already... I'm apologize I didn't do it earlier...

**Comment by smithfarm** [comment]
The only problem I see, assuming all the cherry-picks applied cleanly as the absence of `Conflicts` sections would seem to indicate, is that the last commit is missing the `Signed-off-by` line. But that should have been caught in https://github.com/ceph/teuthology/pull/1476 . . . too late to fix it now.

**Comment by kshtsk** [comment]
Thanks, Nathan

**Pull request merged**
