### PR TITLE
requirements: add libvirt-python for ubuntu

### PR DESCRIPTION
**Pull request by clwluvw**
libvirt-python is needed to import libvirt in python for ubuntu

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
1) The requirements.txt file looks corrupted
2) why the libvirt-python is ubuntu specific?

**Comment by clwluvw** [comment]
> 1. The requirements.txt file looks corrupted
I've made it with pip-compile like a command above the file and I don't know why it generates it like this! Maybe because of the version or..? Is there anything I should specify in my command to be generated as before?

> 2. why the libvirt-python is ubuntu specific?
I've tested it in ubuntu env and I thought it's just needed for ubuntu because I think it's working for others that using centOS :D

**Comment by kshtsk** [comment]
> > 1. why the libvirt-python is ubuntu specific?
> 
> I've tested it in ubuntu env and I thought it's just needed for ubuntu because I think it's working for others that using centOS :D

Which teuthology code are you referring that you've tested with.
Basically the libvirt-python is not requirements because there is a system package supposed to be preinstalled. It is deployed by ceph-cm-ansible role AFAIK.

**Comment by clwluvw** [comment]
> > > 1. why the libvirt-python is ubuntu specific?
> > 
> > 
> > I've tested it in ubuntu env and I thought it's just needed for ubuntu because I think it's working for others that using centOS :D
> 
> Which teuthology code are you referring that you've tested with.
> Basically the libvirt-python is not requirements because there is a system package supposed to be preinstalled. It is deployed by ceph-cm-ansible role AFAIK.

If I set `ceph_cm_ansible: False` it won't be installed.

**Comment by kshtsk** [comment]
> > > > 1. why the libvirt-python is ubuntu specific?
> > > 
> > > 
> > > I've tested it in ubuntu env and I thought it's just needed for ubuntu because I think it's working for others that using centOS :D
> > 
> > 
> > Which teuthology code are you referring that you've tested with.
> > Basically the libvirt-python is not requirements because there is a system package supposed to be preinstalled. It is deployed by ceph-cm-ansible role AFAIK.
> 
> If I set `ceph_cm_ansible: False` it won't be installed.

No, it is not for testnodes. It is teuthology role. https://github.com/ceph/ceph-cm-ansible/blob/master/roles/teuthology/vars/apt_systems.yml#L9

**Comment by clwluvw** [comment]
> > > > > 1. why the libvirt-python is ubuntu specific?
> > > > 
> > > > 
> > > > I've tested it in ubuntu env and I thought it's just needed for ubuntu because I think it's working for others that using centOS :D
> > > 
> > > 
> > > Which teuthology code are you referring that you've tested with.
> > > Basically the libvirt-python is not requirements because there is a system package supposed to be preinstalled. It is deployed by ceph-cm-ansible role AFAIK.
> > 
> > 
> > If I set `ceph_cm_ansible: False` it won't be installed.
> 
> No, it is not for testnodes. It is for the role of teuthology itself. https://github.com/ceph/ceph-cm-ansible/blob/master/roles/teuthology/vars/apt_systems.yml#L9

Oh now I see what you mean with:
> Which teuthology code

I'm running it teuthology-suite manually from this repo and so I just installed the bootstrap here.

**Comment by kshtsk** [comment]
Now, I am not sure, maybe you better add this dep to the bootstrap script?

**Comment by clwluvw** [comment]
> Now, I am not sure, maybe you better add this dep to the bootstrap script?

I see all the python packages are installing from `requirements.txt`! Why should I move it to the bootstrap script?

**Comment by kshtsk** [comment]
> > Now, I am not sure, maybe you better add this dep to the bootstrap script?
> 
> I see all the python packages are installing from `requirements.txt`! Why should I move it to the bootstrap script?

Because it is supposed to be a system package, otherwise you need to fix the ceph-cm-ansible role to not include libvirt-python, however, it needs to check if ceph-cm-ansible still work fine.

**Comment by clwluvw** [comment]
> > > Now, I am not sure, maybe you better add this dep to the bootstrap script?
> > 
> > 
> > I see all the python packages are installing from `requirements.txt`! Why should I move it to the bootstrap script?
> 
> Because it is supposed to be a system package, otherwise you need to fix the ceph-cm-ansible role to not include libvirt-python, however, it needs to check if ceph-cm-ansible still work fine.

I think removing it from ceph-cm-ansible and add it here would be better because ceph-cm-ansible is running bootstrap too: https://github.com/ceph/ceph-cm-ansible/blob/master/roles/teuthology/tasks/setup_users.yml#L75

@kshtsk If it's okay let me know to submit a patch there too.

**Comment by kshtsk** [comment]
> > > > Now, I am not sure, maybe you better add this dep to the bootstrap script?
> > > 
> > > 
> > > I see all the python packages are installing from `requirements.txt`! Why should I move it to the bootstrap script?
> > 
> > 
> > Because it is supposed to be a system package, otherwise you need to fix the ceph-cm-ansible role to not include libvirt-python, however, it needs to check if ceph-cm-ansible still work fine.
> 
> I think removing it from ceph-cm-ansible and add it here would be better because ceph-cm-ansible is running bootstrap too: https://github.com/ceph/ceph-cm-ansible/blob/master/roles/teuthology/tasks/setup_users.yml#L75
> 
> @kshtsk If it's okay let me know to submit a patch there too.

I guess there was a reason why python-libvirt has been installing via system packages, maybe to be the same version as system libvirt package.

**Comment by clwluvw** [comment]
@kshtsk I've tested with the system package and it won't work again. I've also set the virtualenv config to use system packages but it again failed!

**Comment by kshtsk** [comment]
> @kshtsk I've tested with the system package and it won't work again. I've also set the virtualenv config to use system packages but it again failed!

again, what exactly do you test? sepia teuthology server is running on ubuntu

**Comment by kshtsk** [comment]
No response from contributor more than two weeks.
Thank you for contribution feel free to create another PR with better explanation.

**Pull request closed without merging**
