### PR TITLE
task/selinux: Ignore source context of ping_t

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/55443

### CODE REVIEW

**Comment by badone** [comment]
Bump

**Comment by dmick** [comment]
Dear God I hate selinux.  

1) does this not make the ping fail?  Is that not an issue for the test?
2) is this fix "ignoring the source context of ping_t", or is it ignoring a *mismatch* in source context for purposes of masking the error for teuthology?

**Comment by kshtsk** [comment]
rebase needed

**Review by yuriw — APPROVED** [review]

**Comment by badone** [comment]
> rebase needed

I've rebased my branch, although it's not clear at all that a rebase was needed and there were no conflicts.

**Comment by badone** [comment]
> Dear God I hate selinux.
> 
>     1. does this not make the ping fail?  Is that not an issue for the test?

It's not clear what invokes the ping to me. The tests fail because the selinux denial is found in the logs. With this commit the tests pass. I think for whatever reason the powercycle tests invoke 'ping' indirectly.
> 
>     2. is this fix "ignoring the source context of ping_t", or is it ignoring a _mismatch_ in source context for purposes of masking the error for teuthology?

I'm not sure what you mean exactly by mismatch. As the tracker indicates this appears to be a system problem which has not been resolved therefore I am asking teuthology to ignore this denial so the tests will pass.

**Comment by dmick** [comment]
What is the source context, and how does this change ignore it?

**Comment by badone** [comment]
After talking to Dan I'm going to try and make this more specific.

**Comment by kshtsk** [comment]
Updates?

**Comment by badone** [comment]
> Updates?

If you have seen this in a recent test could you post details in the tracker?

**Comment by kshtsk** [comment]
> > Updates?
> 
> If you have seen this in a recent test could you post details in the tracker?

@badone No, I haven't, just wondering if we still need this, if so, why it is still DNM, more than a year passed since it's created.

**Comment by badone** [comment]
Closing unless or until it's seen again.

**Pull request closed without merging**
