### PR TITLE
replace deprecated nose dependency with pynose

### PR DESCRIPTION
**Pull request by cbodley**
after upgrading teuthology to centos 9 and python 3.10, the rgw multisite test suite now fails to invoke nosetests with:

> AttributeError: module 'collections' has no attribute 'Callable'

this is a known issue tracked in https://github.com/nose-devs/nose/issues/1127

Shilpa found a new 'pynose' package which claims that:

> This version of nose is compatible with Python 3.7+ (including 3.13+).

replace the nose dependency that i initially added in https://github.com/ceph/teuthology/pull/1069 with the current version 1.5.1 of pynose

to prepare this pr, i first changed setup.cfg then ran:

> ./update-requirements.sh -P "pynose==1.5.1"

Fixes: https://tracker.ceph.com/issues/66183

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @zmc. not sure this works yet, tests pending in https://pulpito.ceph.com/cbodley-2024-05-23_16:42:18-rgw:multisite-wip-boost-asio-spawn-unlock-distro-default-smithi/

i first tried https://pulpito.ceph.com/cbodley-2024-05-23_16:37:04-rgw:multisite-wip-boost-asio-spawn-unlock-distro-default-smithi/ but this wip-pynose branch hadn't made it to git.ceph.com yet?

cc @smanjara

**Comment by zmc** [comment]
Sounds good. If the tests pass, feel free to merge. If there are more issues, I can re-review.

**Comment by smanjara** [comment]
the tests failed due to multisite related errors. Scheduled a new run with two zone configuration

https://pulpito.ceph.com/smanjara-2024-05-23_19:43:45-rgw:multisite-wip-shilpa-multisite-tests-distro-default-smithi/7723368/

**Comment by cbodley** [comment]
@smanjara we'll likely need to reconsider use of this library based on licensing discussions in https://github.com/mdmintz/pynose/issues/16

thanks @adamemerson for the heads-up

**Comment by smanjara** [comment]
> @smanjara we'll likely need to reconsider use of this library based on licensing discussions in [mdmintz/pynose#16](https://github.com/mdmintz/pynose/issues/16)
> 
> thanks @adamemerson for the heads-up

ack

**Pull request merged**
