### PR TITLE
update ansible package from ansible PPA

### PR DESCRIPTION
**Pull request by vasukulkarni**
Fixes: http://tracker.ceph.com/issues/21574

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-10-18_22:11:05-ceph-ansible-luminous-distro-basic-ovh/

**Comment by yuriw** [comment]
@vasukulkarni can we run `ceph-ansible` on nodes other then mon.0 ?

**Comment by vasukulkarni** [comment]
@yuriw yes that part i missed, but we can take it up later, not using anislble ppa packages seems be causing issue.

**Comment by yuriw** [comment]
@vasukulkarni it'd be nice to have as @leseb requested it as part of underlining tracker.

**Comment by ktdreyer** [comment]
:+1:

**Comment by vasukulkarni** [comment]
Rerun after the cleanup commit http://pulpito.ceph.com/vasu-2017-10-19_18:44:15-ceph-ansible-luminous-distro-basic-ovh/

**Pull request merged**
