### PR TITLE
Makes (de)canonicalize_hostname ready to empty domains

### PR DESCRIPTION
**Pull request by ryg-**
Add to calls misc.canonicalize_hostname and misc.decanonicalize_hostname
support of empty domains, created tests for it.

### CODE REVIEW

**Comment by ryg-** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
ok to test

**Comment by kshtsk** [comment]
@ryg- I guess you need to add a unittest to cover this kind of failures (see the logs from susebot):
```
2020-09-16T20:37:37.935 DEBUG:teuthology.lock.ops:locked ubuntu@target-pr-1559-016..ovh.suse.de, ubuntu@target-pr-1559-017..ovh.suse.de, ubuntu@target-pr-1559-018..ovh.suse.de

```

**Comment by ryg-** [comment]
> @ryg- I guess you need to add a unittest to cover this kind of failures (see the logs from susebot):
> 
> ```
> 2020-09-16T20:37:37.935 DEBUG:teuthology.lock.ops:locked ubuntu@target-pr-1559-016..ovh.suse.de, ubuntu@target-pr-1559-017..ovh.suse.de, ubuntu@target-pr-1559-018..ovh.suse.de
> ```

yes, bug was in code and not covered by tests. Now it should be fixed

**Comment by ryg-** [comment]
ok to test

**Comment by ryg-** [comment]
@susebot run deploy

**Comment by ryg-** [comment]
tested in sepia
http://pulpito.front.sepia.ceph.com/ryg--2020-09-22_19:35:53-suse:tier0-nautilus-none-basic-mira/

**Review by toabctl — DISMISSED** [review]

**Review by kshtsk — APPROVED** [review]

**Pull request merged**
