### PR TITLE
[DNM] Add xfs bug to syslog error exceptions

### PR DESCRIPTION
**Pull request by djgalloway**
Fixes: http://tracker.ceph.com/issues/17003

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
Is there evidence that this is truly something we should ignore?

**Comment by djgalloway** [comment]
http://oss.sgi.com/archives/xfs/2016-06/msg00206.html maybe?

I also found http://tracker.ceph.com/issues/3058

**Comment by djgalloway** [comment]
@jcsp @gregsfortytwo Can you guys weigh in on http://tracker.ceph.com/issues/17003#note-5 please?

**Comment by gregsfortytwo** [comment]
Yeah, we have hit that with our own code before. A filter would need to check for xfs specifically. :(

**Comment by idryomov** [comment]
Please don't do this - see my comment on the tracker.

**Pull request closed without merging**
