### PR TITLE
supervisor: To preserve logs, delay nuking

### PR DESCRIPTION
**Pull request by zmc**
The bonus commit will help us identify which hosts fail to reconnect in the future.

### CODE REVIEW

**Comment by djgalloway** [comment]
I think df5073b fixes https://tracker.ceph.com/issues/51944.  Can you add that to the commit message?

**Comment by zmc** [comment]
Good point @djgalloway - done

**Review by djgalloway — APPROVED** [review]
Makes sense to me logically

**Review by jdurgin — APPROVED** [review]

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by zmc** [comment]
@kshtsk it looks like there was an unrelated problem with the deployment

**Comment by kshtsk** [comment]
> @kshtsk it looks like there was an unrelated problem with the deployment

right... something new poped up, I will look into it if I can fix it

**Comment by kshtsk** [comment]
gonna trigger another one for reproducibility

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
looks like `pip install -U pip` is failing... if it can wait another day, let me look at it tomorrow
```
    stdout: Collecting Jinja2==2.9.5
      Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340 kB)
    Collecting Mako==1.0.2
      Downloading Mako-1.0.2.tar.gz (564 kB)
    Collecting MarkupSafe==1.1.1
      Downloading MarkupSafe-1.1.1-cp36-cp36m-manylinux2010_x86_64.whl (32 kB)
    Collecting WebOb==1.8.6
      Downloading WebOb-1.8.6-py2.py3-none-any.whl (114 kB)
    Collecting WebTest==2.0.18
      Downloading WebTest-2.0.18.zip (88 kB)
    Collecting beautifulsoup4==4.3.2
      Downloading beautifulsoup4-4.3.2.tar.gz (143 kB)
    Collecting flake8
      Downloading flake8-3.9.2-py2.py3-none-any.whl (73 kB)
    Collecting ipdb==0.8.1
      Downloading ipdb-0.8.1.zip (20 kB)
  
    :stderr:     ERROR: Command errored out with exit status 1:
         command: /home/pulpito/pulpito/virtualenv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qm56h9r3/ipdb_e42076a400604105890be1cd2c728d9a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qm56h9r3/ipdb_e42076a400604105890be1cd2c728d9a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-paj59o0x
             cwd: /tmp/pip-install-qm56h9r3/ipdb_e42076a400604105890be1cd2c728d9a/
        Complete output (1 lines):
        error in ipdb setup command: use_2to3 is invalid.
        ----------------------------------------
    WARNING: Discarding https://files.pythonhosted.org/packages/cb/ed/cf9b80923dfee3b861d18c43e68793e52a81e51a7534f81c665e71b1642d/ipdb-0.8.1.zip#sha256=1763d1564113f5eb89df77879a8d3213273c4d7ff93dcb37a3070cdf0c34fd7c (from https://pypi.org/simple/ipdb/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Could not find a version that satisfies the requirement ipdb==0.8.1 (from versions: 0.1dev-r1556, 0.1dev-r1713, 0.1dev-r1714, 0.1dev-r1716, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7, 0.7.1, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11, 0.12, 0.12.1, 0.12.2, 0.12.3.dev0, 0.12.3, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9)
    ERROR: No matching distribution found for ipdb==0.8.1

```

**Comment by kshtsk** [comment]
ah, that is `pip install -r requirements.txt` issue:
```
ERROR: Could not find a version that satisfies the requirement ipdb==0.8.1 (from versions: 0.1dev-r1556, 0.1dev-r1713, 0.1dev-r1714, 0.1dev-r1716, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7, 0.7.1, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11, 0.12, 0.12.1, 0.12.2, 0.12.3.dev0, 0.12.3, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9)
ERROR: No matching distribution found for ipdb==0.8.1
```
and this looks weird, because 0.8.1 version is definetly in he list.

**Comment by kshtsk** [comment]
@zmc maybe this will help https://github.com/ceph/pulpito/pull/86

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
I already see pulpito is running http://51.83.105.118:8081/runner-2021-09-15_22:29:20-smoke-octopus-distro-basic-gra/

**Pull request merged**
