### PR TITLE
teuthology/misc: use parallel gzip to compress logs

### PR DESCRIPTION
**Pull request by batrick**
I was hoping to evaluate this in testing but apparently this is one of those parts of teuthology that needs merged into main to run. Anyway, I expect this should dramatically reduce the time teuthology spends compressing logs at the end of long tests.

### CODE REVIEW

**Comment by zmc** [comment]
@batrick if you push your branch to this repo, you can use the `--teuthology-branch` arg for `teuthology-suite`. The supervisor will be run using that branch.

**Comment by batrick** [comment]
> @batrick if you push your branch to this repo, you can use the `--teuthology-branch` arg for `teuthology-suite`. The supervisor will be run using that branch.

I tried but it did not seem to run this updated code. My u8nderstanding is that some parts of teuthology are always run from `main` via the teuthology host. I wonder if this is one of those parts.

Or maybe I screwed up... that's possible too!

**Comment by batrick** [comment]
ooooh... I wonder if this is dead code. This work is now done in Ceph in `qa/tasks/ceph.py`

**Comment by zmc** [comment]
Here's where the dispatcher spawns the supervisor (which in turn spawns the job process): https://github.com/ceph/teuthology/blob/main/teuthology/dispatcher/__init__.py#L154-L160
Just above that, it's calling `prep_job` and setting `teuth_bin_path`: https://github.com/ceph/teuthology/blob/main/teuthology/dispatcher/__init__.py#L141-L148
Here in `prep_job` is where the requested branch is cloned: https://github.com/ceph/teuthology/blob/main/teuthology/worker.py#L174-L176

**Comment by batrick** [comment]
Thanks for sketching that out @zmc!

Here's the ceph fix for this: https://github.com/ceph/ceph/pull/50616

Although maybe we still want this to be merged?

**Comment by zmc** [comment]
We might - can we run it through, say, a job from the smoke suite?

**Comment by batrick** [comment]
> We might - can we run it through, say, a job from the smoke suite?

Here's a run with fs:workload: https://pulpito.ceph.com/pdonnell-2023-03-22_17:35:48-fs:workload-wip-pdonnell-testing-20230322.005419-distro-default-smithi/

**Comment by KennethSeruuma** [comment]
Hello members, I am an Outreachy intern, hoping to be part of this open source contributing community. @zmc , @batrick.

**Comment by batrick** [comment]
> Hello members, I am an Outreachy intern, hoping to be part of this open source contributing community. @zmc , @batrick.

Hi Kenneth, who is your mentor? Please feel free to communicate via the mailing lists to get more involved. These pull requests are not the right venue as you may get lost. :)

**Comment by batrick** [comment]
@zmc thanks for checking on it. This looks good to me:

https://pulpito.ceph.com/zack-2023-03-29_22:34:19-fs-wip-pdonnell-testing-20230329.131031-distro-default-smithi/

**Review by zmc — APPROVED** [review]
Awesome, thanks Patrick!

**Comment by KennethSeruuma** [comment]
> 

ok. Thanks @batrick for the advice. My mentors are Sirivadhna, and Mathuria. I wonder whether they are present on this platform.

**Pull request merged**
