### PR TITLE
Add Q&A for customization lab setup notes and fix Readme reference

### PR DESCRIPTION
**Pull request by Ericyuanhui**
Signed-off-by: Ericyuanhui <yuanhui.xu@intel.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@gregsfortytwo is that something we can make use of?
@Ericyuanhui do you still want to merge this?

**Comment by gregsfortytwo** [comment]
@kshtsk if it works then it'd be nice to have, but I don't have the bandwidth to try it out.

**Comment by kshtsk** [comment]
@smithfarm not sure if we need this, maybe just close it?

**Comment by smithfarm** [comment]
@Ericyuanhui if this is still current, please open a new PR with the cleanups in a separate commit (or maybe even in a completely separate PR). As it is, it's difficult, at least for me, to distinguish the substantive changes from the cleanups.

**Pull request closed without merging**
