### PR TITLE
create a teuthology integration test task

### PR DESCRIPTION
**Pull request by andrewschoen**
See, http://tracker.ceph.com/issues/10736

This creates a new task 'tests' that when included will run a set of integration tests against teuthology.  They are considered integration tests because each tests are passed the ctx and config args that any regular task would.  This means they can operate against the current cluster to verify things.  I've only included a few tests as a starting point.  We plan to pair this task with a qa suite that performs other common tasks.

I've yet to write the qa suite, but I wanted to post this for early reviews and opinions.

Some sample log output from this task.

```
2015-02-05 11:26:06,297.297 INFO:teuthology.run_tasks:Running task tests...
2015-02-05 11:26:06,440.440 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_os_type Passed
2015-02-05 11:26:06,442.442 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_os_version Passed
2015-02-05 11:26:06,443.443 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_machine_type Passed
2015-02-05 11:26:06,445.445 INFO:teuthology.orchestra.run.magna067:Running (working as expected, nothing to see here): "python -c 'assert False'"
2015-02-05 11:26:06,494.494 INFO:teuthology.orchestra.run.magna067.stderr:Traceback (most recent call last):
2015-02-05 11:26:06,495.495 INFO:teuthology.orchestra.run.magna067.stderr:  File "<string>", line 1, in <module>
2015-02-05 11:26:06,495.495 INFO:teuthology.orchestra.run.magna067.stderr:AssertionError
2015-02-05 11:26:06,497.497 INFO:teuthology.task.tests:test_run:TestRun.test_command_failed_label Passed
2015-02-05 11:26:06,500.500 INFO:teuthology.orchestra.run.magna067:Running: "python -c 'assert False'"
2015-02-05 11:26:06,547.547 INFO:teuthology.orchestra.run.magna067.stderr:Traceback (most recent call last):
2015-02-05 11:26:06,548.548 INFO:teuthology.orchestra.run.magna067.stderr:  File "<string>", line 1, in <module>
2015-02-05 11:26:06,548.548 INFO:teuthology.orchestra.run.magna067.stderr:AssertionError
2015-02-05 11:26:06,550.550 INFO:teuthology.task.tests:test_run:TestRun.test_command_failed_no_label Passed
2015-02-05 11:26:06,552.552 INFO:teuthology.orchestra.run.magna067:Running: 'python -c \'print \'"\'"\'hi\'"\'"\'\''
2015-02-05 11:26:06,653.653 INFO:teuthology.task.tests:test_run:TestRun.test_command_success Passed
2015-02-05 11:26:06,655.655 INFO:teuthology.task.tests:OK. All tests passed!
```

### CODE REVIEW

**Comment by andrewschoen** [comment]
This might very well have to change as I write the suite to go along with it, but wanted to throw it out there for any early feedback.  Or ideas for other tests to include would be appreciated.

**Comment by zmc** [comment]
test this please

**Comment by andrewschoen** [comment]
Maybe we can move some of theses tests here: https://github.com/ceph/teuthology/blob/master/teuthology/test/integration/test_suite.py

Also, there is this: https://github.com/ceph/teuthology/blob/master/teuthology/task/tasktest.py

**Comment by andrewschoen** [comment]
Tox didn't like the duplicate pytest requirement, it seems happier now though.

**Comment by zmc** [comment]
This is so cool.

**Pull request merged**
