### PR TITLE
Add bootstrap support for LinuxMint

### PR DESCRIPTION
**Pull request by ishanrai05**
Tested on Linux Mint 19.3

Signed-off-by: ishanrai05 <ishanrai05@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
ok to test

**Comment by kshtsk** [comment]
ok to test

**Comment by kshtsk** [comment]
I wonder is LinuxMint based on Debian or Ubuntu distros?

**Comment by ishanrai05** [comment]
@kshtsk  LinuxMint is based on Ubuntu

**Comment by kshtsk** [comment]
rebase required

**Comment by ishanrai05** [comment]
@kshtsk done

**Pull request merged**
