### PR TITLE
make teuthology-openstack great again

### PR DESCRIPTION
**Pull request by kshtsk**
Not only making it working again this PR contains several useful features and fixes.
Among them teuthology-openstack run several clusters per region.

### CODE REVIEW

**Comment by kshtsk** [comment]
This PR is supposed to be a replacement for #1028

**Comment by kshtsk** [comment]
This PR is hopefully the latest big portion of commits with features and functionality developed in suse/teuthology repo. Though, minor patches can be submitted later. After merging the suse/teutholgy master branch will be declared as legacy and renamed correspondingly, afterwards it will be a copy of ceph/teuthology master.

**Comment by smithfarm** [comment]
Hm, I wonder if we need to reintroduce `buildpackages`. It seems like dead code to me.

**Comment by kshtsk** [comment]
> Hm, I wonder if we need to reintroduce `buildpackages`. It seems like dead code to me.

This is a good point, however it will be not trivial to remove it from this PR, rather than issue another cleanup commit on top of it. However, we were able to build ceph rpms package without shaman.

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@gregsfortytwo could you please review

**Comment by kshtsk** [comment]
@gregsfortytwo thanks, that is expected.

**Comment by kshtsk** [comment]
Following requirements.txt was proof to be working with changes in this PR.
```
--index-url https://pypi.python.org/simple/

-e .

boto==2.39.0
cffi==1.11.2
cliff==2.2.0
cryptography==2.7
fasteners==0.14.1
keystoneauth1==2.12.1
idna==2.6
openstacksdk==0.9.5
os-client-config==1.21.1
osc-lib==1.1.0
oslo.config==3.17.0
oslo.i18n==3.9.0
oslo.serialization==2.13.0
oslo.utils==3.16.0
pycparser==2.18
pyopenssl==16.2.0
python-cinderclient==1.9.0
python-glanceclient==2.5.0
python-keystoneclient==3.5.0
python-neutronclient==4.1.1
python-novaclient==6.0.0
python-openstackclient==3.2.0
requests==2.18.4
```
It needs to replace the one in master and should be include in deployment testing branch. I do not include it within this PR, because versions of packages are older than in recent `setup.py/teuthology` and could probably break dependencies for `libcloud`.
Though the current python-openstackclient has higher version in the master it is not backward compatible with this code. The corresponding separate PRs of switching to the latest and greatest openstack libraries as well as libcloud will follow.

**Comment by djgalloway** [comment]
This PR broke `teuthology-lock` for me on my workstation.  https://tracker.ceph.com/issues/42543

**Comment by kshtsk** [comment]
> This PR broke `teuthology-lock` for me on my workstation. https://tracker.ceph.com/issues/42543

interesting... this may be because of this 5ac7c2f ?

**Comment by kshtsk** [comment]
> This PR broke `teuthology-lock` for me on my workstation. https://tracker.ceph.com/issues/42543

Could you please try this on the box where you can reproduce this issue
https://github.com/ceph/teuthology/pull/1344

**Comment by djgalloway** [comment]
> > This PR broke `teuthology-lock` for me on my workstation. https://tracker.ceph.com/issues/42543
> 
> Could you please try this on the box where you can reproduce this issue
> #1344

Confirmed.

**Pull request merged**
