### PR TITLE
task.ansible: Allow passing in custom group_vars

### PR DESCRIPTION
**Pull request by zmc**
Up until now, if you wanted to inject vars to a playbook run, you had to
use --extra-vars, which don't behave the same way that group_vars do.
This commit adds that functionality.

We look for a 'group_vars' dict in the task's config object. If it's
there, we create group_vars files with names taken from the keys, and
content taken from the values.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
test this please

**Comment by vasukulkarni** [comment]
@zmc unit tests seems to be failing

**Comment by zmc** [comment]
@vasukulkarni yeah, I'm looking into it. Could be a bug in mock

**Comment by zmc** [comment]
Finally fixed the issue - was a bug (?) in py.test. New one is with our Jenkins jobs:
```
+ echo 'Ensuring latest pip is installed'
Ensuring latest pip is installed
+ /tmp/venv.p5cnFebK9t/bin/pip install --upgrade --exists-action=i --download=/home/jenkins-build/.cache/pip pip

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --download
```

It should have been addressed by https://github.com/ceph/ceph-build/pull/997, but perhaps the changes haven't gotten picked up somehow...?

**Comment by tchaikov** [comment]
retest this please.

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
There was a dependency problem on 172.21.1.49; librados2 12.0.2-1963-g1244c0a-1xenial was installed, preventing qemu-utils from pulling in its dependencies.

**Comment by zmc** [comment]
@vasukulkarni finally ready :)

**Comment by zmc** [comment]
http://pulpito.front.sepia.ceph.com/zack-2018-04-03_01:35:43-cephmetrics-master-distro-basic-ovh/

**Comment by vasukulkarni** [comment]
@zmc thanks for additional fixes 👍

**Pull request merged**
