### PR TITLE
task/full_sequential_finally: run commands on unwind/cleanup

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
tested at http://pulpito.ceph.com/sage-2017-04-20_16:27:42-rados:thrash-wip-snapset---basic-smithi/, works!

**Comment by liewegas** [comment]
..and verified that a failed command throws an exception: http://pulpito.ceph.com/sage-2017-04-20_18:07:33-rados:thrash-wip-snapset---basic-smithi/1049590/

**Comment by zmc** [comment]
Would you be able to add a little docstring text explaining how this is different from `sequential` and `full_sequential`?

**Comment by liewegas** [comment]
thanks!

**Pull request merged**
