### PR TITLE
install: Allow installing python3 packages universally

### PR DESCRIPTION
**Pull request by BlaXpirit**
...by replacing `python3-*` with `python34-*` on CentOS.

This is required so python3-based packages can be specified cleanly in `extra_packages` (like [here](https://github.com/ceph/ceph-qa-suite/compare/wip-ceph-python3#diff-9b1ef2f4528109b07046d9dec615dd08R3)), because packages for CentOS will have a `python34-` prefix and not `python3-`, to follow the existing convention.

Related to https://github.com/ceph/ceph/pull/10208

### CODE REVIEW

**Comment by jdurgin** [comment]
lgtm - a simple approach is all that's needed now

 @zmc what do you think?

**Comment by dmick** [comment]
oy.  what's next, python-342?  :(  one questions the wisdom of the package naming.

**Comment by BlaXpirit** [comment]
(By existing convention I mean https://dl.fedoraproject.org/pub/epel/7/x86_64/p/ *python34*)

**Comment by BlaXpirit** [comment]
ping

**Pull request merged**
