### PR TITLE
lock/ops: remove import to break import loop

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: https://tracker.ceph.com/issues/42256

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
interesting, how to reproduce this issue?

**Comment by kshtsk** [comment]
@ryg- looks like this import was not necessary
Also it is interesting why flake8 didn't say a word regarding this.

**Comment by s0nea** [comment]
I tested the PR locally and it fixes my issue: https://tracker.ceph.com/issues/42255

**Comment by kshtsk** [comment]
> I tested the PR locally and it fixes my issue: https://tracker.ceph.com/issues/42255

which are steps to reproduce?

**Comment by s0nea** [comment]
> > I tested the PR locally and it fixes my issue: https://tracker.ceph.com/issues/42255
> 
> which are steps to reproduce?

@kshtsk the issue happened to me when running https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/run-backend-api-tests.sh

**Comment by kshtsk** [comment]
> > > I tested the PR locally and it fixes my issue: https://tracker.ceph.com/issues/42255
> > 
> > 
> > which are steps to reproduce?
> 
> @kshtsk the issue happened to me when running https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/run-backend-api-tests.sh

it is using cython inside?
https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/run-backend-api-tests.sh#L153

**Comment by rjfd** [comment]
> > 
> > @kshtsk the issue happened to me when running https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/run-backend-api-tests.sh
> 
> it is using cython inside?
> https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/run-backend-api-tests.sh#L153

No, it's just pointing to the location of the ceph python bindings build.

**Comment by kshtsk** [comment]
@rjfd does this run-backend-api-tests.sh run in any teuthology suite?

**Comment by rjfd** [comment]
> @rjfd does this run-backend-api-tests.sh run in any teuthology suite?

No, this is used by dashboard developers to run the same set of tests as in qa/suites/rados/mgr/tasks/dashboard.yaml locally in their own computers using a vstart cluster.

**Comment by kshtsk** [comment]
the moral... we cannot verify this test in automated fashion. have you thought to create teuthology suite for it?

**Comment by rjfd** [comment]
@kshtsk not worth the effort and don't even know if it's possible.

**Pull request merged**
