### PR TITLE
provision.py: implement an OpenStack backend

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/6502

### CODE REVIEW

**Comment by dachary** [comment]
@zmc you should be able to run the integration tests against the OpenStack cluster you have

**Comment by dachary** [comment]
@kapil to test it locally

* download openrc.sh in teuthology/tests/integration/
* customize teuthology/tests/integration/setup-openstack.sh to replace server-create etc. with values relevant to your cluster
* tox -v -e openstack-integration

and report failure ;-) /me being pessimistic

**Comment by zmc** [comment]
@dmick I can't see any of your comments in their actual context... :(

**Comment by zmc** [comment]
There are a *lot* of commits in this PR that are unrelated to OpenStack. I'd really prefer them to be submitted separately for discussion.

**Comment by dachary** [comment]
@zmc ok, I'll restructure this in multiple pull requests.

**Pull request closed without merging**
