### PR TITLE
setup.py: add toml for qa/tasks/cephadm.py

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by tchaikov** [comment]
http://pulpito.front.sepia.ceph.com/swagner-2020-05-26_11:34:30-rados:cephadm-wip-swagner-testing-2020-05-25-0943-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-26_11:58:14-rados:cephadm-wip-swagner-testing-2020-05-25-0943-distro-basic-smithi/

**Comment by toabctl** [comment]
@sebastian-philipp  Out of interest - why does cephadm wants to modify the registries.conf file? This file might be under control of other systems (like ceph-salt).

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp Out of interest - why does cephadm wants to modify the registries.conf file? This file might be under control of other systems (like ceph-salt).

we need to add a caching registry proxy (aka "mirror"), cause dockerhub.io is blocking our requests due to rate limiting.

**Comment by kshtsk** [comment]
@sebastian-philipp what about adding "podman" module to teuthology code base instead of adding some strange stuff to cephadm?

**Comment by kshtsk** [comment]
or is this more related to docker... I can see that on opensuse-15.1 the conf file you're modifying is provided by `libcontainers-common`

**Comment by sebastian-philipp** [comment]
> or is this more related to docker... I can see that on opensuse-15.1 the conf file you're modifying is provided by `libcontainers-common`

yes, I need to patch the existing docker.io registry entry. :+1: for moving this to a different location. But my top priority is to make the qa runs in  sepia working again. there is a lot that we need to refactor here.

**Comment by tchaikov** [comment]
i don't think the difference docker versus podman makes sense here. what we are after is a way to talk to a mirror registry. the client side can be podman or docker.

**Comment by kshtsk** [comment]
> i don't think the difference between docker and podman makes sense here. what we are after is a way to talk to a mirror registry. the client side can be podman or docker.

right, this is why it is better to use `containers` as shorthand for `containers_common` instead of `docker.io`

**Comment by toabctl** [comment]
> @sebastian-philipp Out of interest - why does cephadm wants to modify the registries.conf file? This file might be under control of other systems (like ceph-salt).

sorry for the noise. I thought this is ceph/ceph , not ceph/teuthology. so makes sense now.

**Pull request merged**
