### PR TITLE
bootstrap: make virtualenv version latest

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
old virtualenv will meet some problem.
e.g. pip upgrade check will have some problem in precise virtualenv version 1.7.1.2

Maybe we could make sure we have the latest virtualenv like pip/setuptools

### CODE REVIEW

**Comment by zmc** [comment]
This doesn't work as written:
```
zack@teuthology:~/teuthology$ pip install --upgrade virtualenv
Collecting virtualenv
  Downloading virtualenv-15.0.1-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 164kB/s
Installing collected packages: virtualenv
  Found existing installation: virtualenv 13.1.2
    Uninstalling virtualenv-13.1.2:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/bin/virtualenv'
```

**Comment by zmc** [comment]
ok to test

**Comment by Vicente-Cheng** [comment]
@zmc 
hi zack, 

sorry about the testing failure. (I miss the permission problem)
could I could add `sudo` to complete the pip install?
I am not sure because in next lines the pip install didn't use `sudo` to complete install.
`pip install virtualenv`
how did you think?

or did we have a better way to ensure the virtualenv version?

thanks!!!
vicente

**Comment by ktdreyer** [comment]
Time to drop support for running on Precise?

**Comment by zmc** [comment]
@Vicente-Cheng unfortunately using sudo with pip isn't something we'll want to put into this bootstrap. As @ktdreyer mentioned, we're losing our ability to support Precise. Would you be able to upgrade to Trusty at least?

We have a master teuthology node running Trusty and it works quite well for us.

**Comment by Vicente-Cheng** [comment]
hi zack, @zmc

OK!, I understand your means.
Would like to upgrade to trusty.

thanks for explaining : )

close it

**Pull request closed without merging**
