### PR TITLE
implement teuthology_path similar to suite_path

### PR DESCRIPTION
**Pull request by dachary**
In case we want to reference a local directory instead of reseting from
a clone of teuthology.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by zmc** [comment]
Seems like we should have this documented somewhere...

**Comment by dachary** [comment]
@zmc ooops forgot to update docs/siteconfig.rst accordingly. Done and repushed !

**Comment by dachary** [comment]
test this please

**Comment by zmc** [comment]
One difference between this PR and ``suite_path`` is that the latter is implemented as a flag for ``teuthology-suite`` whereas this ``teuthology_path`` is an item in ``teuthology.yaml``. I imagine you have reasons for this, and that's fine. What I'd like to see, though, is the default set in ``teuthology.config`` - would you mind doing that?

**Comment by dachary** [comment]
updated & repushed !

**Pull request merged**
