### PR TITLE
suite: allow `--rerun` to run full set of failed tests

### PR DESCRIPTION
**Pull request by tchaikov**
this change allows us to `--rerun` the full set of failed tests.

### CODE REVIEW

**Comment by tchaikov** [comment]
Don't merge... the filter still cannot match all failed tests.

**Comment by vasukulkarni** [comment]
@tchaikov how is '$' linked to rerun and filters? shouldn't rerun just use the previous run name + filter out failed tests with exact job config for rerun, so whatever fragments we had before will be used as is for rerun?

**Comment by zmc** [comment]
@vasukulkarni The commit message for 2334b94e4bf7f6632939f22c359d16db2b5d565a explains the issue

**Comment by vasukulkarni** [comment]
@zmc I read that and my question is why is $ or the folder structure even important to reconstruct the yaml(match filter etc),  suppose a job ran 2 tests  in {run_folder/teuthology.yaml run_folder/teuthology.yaml} and failed for 2nd one, all the information to reconstruct 2.yaml is in the run folder, the randomness of original folder structure shouldn't matter, If the current rerun is using local dir structure, it should definitely be fixed.

**Comment by tchaikov** [comment]
@vasukulkarni i amended the commit message of the commit addressing this issue. hopefully it's easier to digest.

**Comment by tchaikov** [comment]
@zmc i rewrote the fix so the syntax error should have gone now.

**Comment by tchaikov** [comment]
retest this please

**Comment by zmc** [comment]
Now it's a unit test that's failing :-/

**Comment by tchaikov** [comment]
@zmc but i don't think it's related to my change, am i right?

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
@zmc ping?

**Comment by zmc** [comment]
@tchaikov apologies; merging. Thanks!

**Comment by yuriw** [comment]
@tchaikov if no `--seed xxx` during scheduling , will any `seed` info be stored in the logs ?

**Pull request merged**
