### PR TITLE
teuthology/scrape: Fix bad backtrace parsing in Teuthology.log

### PR DESCRIPTION
**Pull request by kamoltat**
Problem:

- confusing warning message stating that the back trace is malformed

- We kept adding to the backtrace buffer even when we exceeded the `MAX_BT_LINES`

Solution:

- Correct the warning message to be "Ignoring backtrace that exceeds MAX_BT_LINES"
- reset the buffer once we exceeded MAX_BT_LINES
- Added some cases where we detect start/end of back trace.

Fixes: https://tracker.ceph.com/issues/62445

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
Thanks!

**Review by zmc — APPROVED** [review]
Good catch!

**Comment by zmc** [comment]
The docs build failure should be addressed by https://github.com/sphinx-doc/sphinx/pull/11613

**Comment by kamoltat** [comment]
@zmc Thanks for filing the PR to fix the sphinx issue :)

I tried re-running the CI again after https://github.com/sphinx-doc/sphinx/pull/11613 was merged, but it seems to still be failing with the same error :( I wonder if I need to do something more to get the latest update of the patch in my CI

**Comment by zmc** [comment]
@kamoltat they haven't published a release with the fix yet

**Comment by kamoltat** [comment]
> @kamoltat they haven't published a release with the fix yet

@zmc make sense, should we wait for them to publish the release? IMHO since the CI is not really labelled as required, we can just skip it?

**Comment by zmc** [comment]
@kamoltat it's marked as required, but #1885 is a simple fix

**Comment by kamoltat** [comment]
> @kamoltat it's marked as required, but #1885 is a simple fix

Thanks @zmc

**Pull request merged**
