### PR TITLE
Fix the nuke cli behavior to not reboot on default

### PR DESCRIPTION
**Pull request by vasukulkarni**
cli users have to pass -r to reboot like before, still testing...

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@idryomov that is not required, the -r flag is more clear, just tested this on cli as well as in smoke.

**Comment by idryomov** [comment]
Are you sure?  Did you try nuking a kernel client box with a cephfs filesystem mounted?  With this patch applied, if you don't pass --reboot-all, it'll leave the mount behind. 

If you pass --reboot-all, it'll most likely get stuck trying to sync a filesystem whose OSDs have already been nuked.  That's why we need to pass -f -n to reboot.

**Comment by vasukulkarni** [comment]
I am going to try that on my test node, although the case is very hard to hit in kcephfs teuthology tests.

**Comment by idryomov** [comment]
Well, the premise of #832 was that teuthology-nuke can be invoked at any time...  You should also try nuking a box with a local filesystem mounted on top of krbd.  In fact I'd try it first - the "umount -f doesn't work" comment in remove_kernel_mounts() is from 2011, I think it's been fixed since then and is working for cephfs now.

Doing a normal reboot with a local filesystem mounted on top of krbd and OSDs gone has always been a sure way to lockup the box.  It's probably going to be fixed in the near future, but for now the only way to nuke in this case is to force reboot.

**Comment by vasukulkarni** [comment]
I will add a system reset here

**Comment by vasukulkarni** [comment]
closing, many things changed after this.

**Pull request closed without merging**
