### PR TITLE
update packaging.py

### PR DESCRIPTION
**Pull request by coderSHeE**
made changes on string function and on some operators :

### CODE REVIEW

**Comment by coderSHeE** [comment]
yep :)

**Comment by tchaikov** [comment]
ok to test

**Review by tchaikov — CHANGES_REQUESTED** [review]
these changes seem just wrong. and they are not companied with any explanations.

**Comment by dmick** [comment]
Please use more descriptive titles; the fact that it's a change to packaging.py is obvious, but what does the change accomplish?  "update" is too general.

**Pull request closed without merging**
