### PR TITLE
Unpin gevent

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by zmc** [comment]
Unit tests might pass but I want to make sure teuthology actually works properly before we merge this

**Comment by ktdreyer** [comment]
cheers :beers: for keeping this up to date

**Comment by zmc** [comment]
Against all odds, this all passed in OVH:
http://pulpito.ovh.sepia.ceph.com:8081/zack-2015-10-29_20:51:15-smoke-master---basic-openstack/

Okay one job failed, but I am certain it's unrelated.

**Comment by dachary** [comment]
@zmc needs rebase because of qemu-utils

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

ran **tox -v -e openstack** successfully with these commits.

**Pull request merged**
