### PR TITLE
[teuthology/provision]: Increase number of drives for vps to 4

### PR DESCRIPTION
**Pull request by vasukulkarni**
Related to:  https://github.com/ceph/ceph/pull/16799

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph/pull/16842

**Comment by zmc** [comment]
Why was this necessary?

**Comment by djgalloway** [comment]
Because of https://github.com/ceph/ceph/pull/16842

Or does the job config pass number of disks?

**Comment by vasukulkarni** [comment]
Also mentioned in original comment: Related to: ceph/ceph#16799

**Pull request merged**
