### PR TITLE
suite: implement git_branch_exists with ls-remote

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
@zmc I do not understand why the test for git_ls_remote fails on travis-ci. When I run it locally it is fine. Any idea ?

**Comment by zmc** [comment]
@dachary it looks like the test in question tries to hit the network - that might be the problem, but even if it isn't I'd advocate using mock to avoid doing so

**Comment by dachary** [comment]
@zmc it does not use the network, that's what confuses me. dbeeb67393c2288b4ab8deac89731b7f4d933963 has a fixture creating a local git repository to not be network dependent.

**Comment by dachary** [comment]
@zmc the problem was with git author / email settings, fixed & repushed !

**Pull request merged**
