### PR TITLE
misc.sh(): Don't capture stderr by default

### PR DESCRIPTION
**Pull request by zmc**
If not capturing it, log it.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
The reason for this is:
```
$ openstack image list -f json --property name='teuthology-ubuntu-14.04'
Discovering versions from the identity service failed when creating the password plugin. Attempting to determine version from URL.
[
  {
    "Status": "active",
    "ID": "209f81d9-b96e-42e2-98f0-577725424538",
    "Name": "teuthology-ubuntu-14.04"
  }
```
See https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/auth/identity/generic/base.py#L143-L145

teuthology expected the output to be JSON; the first line in that output clearly breaks that. This commit causes that first line to be logged instead of captured.

**Comment by dmick** [comment]
:thumbsup: just waiting for the check

**Comment by dachary** [comment]
This will effectively hide error messages by default and I'm quite sure that's going to make it very difficult to figure out whatever problem happens next.

**Comment by dmick** [comment]
perhaps it should be log.warning()

**Comment by zmc** [comment]
I'm not sure what you mean, @dachary - stderr is still logged.

**Comment by dachary** [comment]
Hum, strike that, it will display stderr instead of returning it. But the reason why it was not done this way in the first place is because it blocs until the process is finished. Which not only breaks the functionality that allows lines to be displayed as they are printed but will also probably deadlock if the process does not finish because the stdout is full and is not consumed by the parent because it is only waiting on the stderr.

**Comment by zmc** [comment]
I see your new concern and I agree. I can put the stderr processing after the stdout loop.

My issue with using -q on all the openstack calls is that if something more important pops up, we won't see it.

**Comment by dachary** [comment]
The **-q** does not suppress errors, only warnings. And if you put the stderr after the stdout you have another potential deadlock, only the other way around.

**Pull request merged**
