### PR TITLE
nuke: --stale-openstack must cope with disappearing volumes / instances

### PR DESCRIPTION
**Pull request by dachary**
The openstack server/volume show typically takes a few seconds to
complete due to the provider API slowness/throttling. It is possible that
a volume/instance found with openstack server list no longer exists when
running openstack server show to get more information about it.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by zmc** [comment]
Needs a rebase. Also there's a typo in the commit message :)

**Comment by dachary** [comment]
@zmc fixed ! (i hope ?)

**Comment by zmc** [comment]
Just noticed the same typo is in the logging messages!

**Comment by dachary** [comment]
@zmc repushed !

**Pull request merged**
