### PR TITLE
orchestra/cluster: make run parallel and wait

### PR DESCRIPTION
**Pull request by kshtsk**
Make cluster.run able to execute a command in parallel on all
nodes and wait for completion.

In order to run a command in parallel on all nodes of the
cluster, instead of combination:
```
  run.wait(cluster.run(wait=False, args=...))
```
this patch makes it possible to do the same just by:
```
  cluster.run(parallel=True, args=...)
```
the `wait` arguments defaults to True in this case.

Also, the behavior of the method is not changed
when `wait` is set to False (like in the first example),
so it is supposed to be backward compatible.

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by liewegas** [comment]
``sync`` doesn't seem like the right arg name to me.  How about ``parallel``?

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
> `sync` doesn't seem like the right arg name to me. How about `parallel`?

@liewegas the change is made, the parameter changed to _parallel_.

**Comment by kshtsk** [comment]
ping @liewegas @jdurgin

**Comment by kshtsk** [comment]
ping @liewegas @jdurgin

**Comment by kshtsk** [comment]
guys could you please review this again, no feedback for months

**Review by jdurgin — APPROVED** [review]

**Comment by jdurgin** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
ok, we are back now

**Pull request merged**
