### PR TITLE
ceph_ansible: provide devices, monitor_interface, public_network

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by zmc** [comment]
Ugh. On Ubuntu it is ``/sbin/ip`` whereas on CentOS it is``/usr/sbin/ip``. And it's not in ``$PATH``. Hold off on this for the moment.

**Comment by zmc** [comment]
@andrewschoen any idea what happened here?
https://jenkins.ceph.com/job/teuthology-pull-requests/247/console

**Comment by zmc** [comment]
Apparently pushing "rebuild" in Jenkins and waiting ~15min for everything to provision/run doesn't actually update this :(

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
@andrewschoen so this time, test passed but reported failure:
https://jenkins.ceph.com/job/teuthology-pull-requests/249/console

So... where do I file bugs for this CI stuff?

**Comment by zmc** [comment]
test this please

**Comment by andrewschoen** [comment]
test this please

**Comment by dmick** [comment]
testing is broken.  so be it.

**Pull request merged**
