### PR TITLE
Fix setenforce failed while selinux is disabled

### PR DESCRIPTION
**Pull request by zenglg**
Signed-off-by: Linggang Zeng <linggang.zeng@easystack.cn>

### CODE REVIEW

**Comment by zenglg** [comment]
@vasukulkarni 
Thank you for your review.
I test it in my local environment:
```
[teuthworker@teuthology-node-1 teuthology]$ teuthology example.yaml 
2018-10-26 18:37:22,418.418 WARNING:teuthology.report:No job_id found; not reporting results
2018-10-26 18:37:22,420.420 INFO:teuthology.run:Config:
  roles:
  - - mon.0
    - osd.0
  targets:
    plana001: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCavOWTV6nPemptVwA2mdxhfm4o/b/xRKLrAAjqdjdvCmYS5df2wVVL1kbEnHam3qRcVxCT2aGdQWMF7hkCKs4MpV9tsDal7d0P9ApGRE0M4RnhMRc5a8bA2+wHedzQg4Qv1jKLzKysVQoJAqGym/OJguPT3CvOCuYTUe801pWxpAUVeD7J2ahVRThckejExEIDu4Wby4phNXtEV2Qkc+eSmCc4BYYuOMBvZ4xH8CQfoYJYrUoGHWGZu55RZ/fCYGvy2NobGtL7+p6wzYnn/Otctamcv6MGegs+okWJ/8ucs4PPHsOySzV30hTBP1Lohy5j5+MujdR9kV01qNnK4jnn
  tasks:
  - install: null
2018-10-26 18:37:22,420.420 INFO:teuthology.run:Tasks not found; will attempt to fetch
2018-10-26 18:37:22,427.427 INFO:teuthology.repo_utils:Fetching master from upstream
2018-10-26 18:37:27,316.316 INFO:teuthology.repo_utils:Resetting repo at /home/teuthworker/src/github.com_zenglg_ceph-qa-suite_master to branch master
2018-10-26 18:37:27,333.333 INFO:teuthology.run_tasks:Running task internal.check_packages...
2018-10-26 18:37:27,333.333 INFO:teuthology.task.internal:Checking packages...
2018-10-26 18:37:27,333.333 INFO:teuthology.task.internal:Checking packages skipped, missing os_type 'None' or ceph hash 'None'
2018-10-26 18:37:27,333.333 INFO:teuthology.run_tasks:Running task internal.buildpackages_prep...
2018-10-26 18:37:27,333.333 INFO:teuthology.task.internal:no buildpackages task found
2018-10-26 18:37:27,333.333 INFO:teuthology.run_tasks:Running task internal.save_config...
2018-10-26 18:37:27,333.333 INFO:teuthology.task.internal:Saving configuration
2018-10-26 18:37:27,334.334 INFO:teuthology.run_tasks:Running task internal.check_lock...
2018-10-26 18:37:27,334.334 INFO:teuthology.task.internal.check_lock:Checking locks...
2018-10-26 18:37:27,365.365 INFO:teuthology.run_tasks:Running task internal.add_remotes...
2018-10-26 18:37:27,365.365 INFO:teuthology.task.internal:roles: ubuntu@plana001.easystack.cn - ['mon.0', 'osd.0']
2018-10-26 18:37:27,365.365 INFO:teuthology.run_tasks:Running task console_log...
2018-10-26 18:37:27,390.390 INFO:teuthology.run_tasks:Running task internal.connect...
2018-10-26 18:37:27,391.391 INFO:teuthology.task.internal:Opening connections...
2018-10-26 18:37:27,486.486 INFO:teuthology.run_tasks:Running task internal.push_inventory...
2018-10-26 18:37:27,486.486 INFO:teuthology.orchestra.run.plana001:Running: 'uname -m'
2018-10-26 18:37:27,565.565 INFO:teuthology.orchestra.run.plana001.stdout:x86_64
2018-10-26 18:37:27,566.566 INFO:teuthology.orchestra.run.plana001:Running: 'cat /etc/os-release'
2018-10-26 18:37:27,648.648 INFO:teuthology.orchestra.run.plana001.stdout:NAME="CentOS Linux"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:VERSION="7 (Core)"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:ID="centos"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:ID_LIKE="rhel fedora"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:VERSION_ID="7"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:PRETTY_NAME="CentOS Linux 7 (Core)"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:ANSI_COLOR="0;31"
2018-10-26 18:37:27,649.649 INFO:teuthology.orchestra.run.plana001.stdout:CPE_NAME="cpe:/o:centos:centos:7"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:HOME_URL="https://www.centos.org/"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:BUG_REPORT_URL="https://bugs.centos.org/"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:CENTOS_MANTISBT_PROJECT="CentOS-7"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:CENTOS_MANTISBT_PROJECT_VERSION="7"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:REDHAT_SUPPORT_PRODUCT="centos"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:REDHAT_SUPPORT_PRODUCT_VERSION="7"
2018-10-26 18:37:27,650.650 INFO:teuthology.orchestra.run.plana001.stdout:
2018-10-26 18:37:27,651.651 INFO:teuthology.lock.ops:Updating plana001.easystack.cn on lock server
2018-10-26 18:37:27,667.667 INFO:teuthology.run_tasks:Running task internal.serialize_remote_roles...
2018-10-26 18:37:27,667.667 INFO:teuthology.run_tasks:Running task internal.check_conflict...
2018-10-26 18:37:27,667.667 INFO:teuthology.task.internal:Checking for old test directory...
2018-10-26 18:37:27,667.667 INFO:teuthology.orchestra.run.plana001:Running: "test '!' -e /home/ubuntu/cephtest"
2018-10-26 18:37:27,715.715 INFO:teuthology.run_tasks:Running task internal.check_ceph_data...
2018-10-26 18:37:27,715.715 INFO:teuthology.task.internal:Checking for non-empty /var/lib/ceph...
2018-10-26 18:37:27,715.715 INFO:teuthology.orchestra.run.plana001:Running: 'test -z $(ls -A /var/lib/ceph)'
2018-10-26 18:37:27,794.794 INFO:teuthology.orchestra.run.plana001.stderr:ls: cannot open directory /var/lib/ceph: Permission denied
2018-10-26 18:37:27,795.795 INFO:teuthology.run_tasks:Running task internal.vm_setup...
2018-10-26 18:37:27,816.816 INFO:teuthology.run_tasks:Running task internal.base...
2018-10-26 18:37:27,816.816 INFO:teuthology.task.internal:Creating test directory...
2018-10-26 18:37:27,816.816 INFO:teuthology.orchestra.run.plana001:Running: 'mkdir -p -m0755 -- /home/ubuntu/cephtest'
2018-10-26 18:37:27,863.863 INFO:teuthology.run_tasks:Running task internal.archive_upload...
2018-10-26 18:37:27,863.863 INFO:teuthology.run_tasks:Running task internal.archive...
2018-10-26 18:37:27,863.863 INFO:teuthology.task.internal:Creating archive directory...
2018-10-26 18:37:27,864.864 INFO:teuthology.orchestra.run.plana001:Running: 'install -d -m0755 -- /home/ubuntu/cephtest/archive'
2018-10-26 18:37:27,942.942 INFO:teuthology.run_tasks:Running task internal.coredump...
2018-10-26 18:37:27,942.942 INFO:teuthology.task.internal:Enabling coredump saving...
2018-10-26 18:37:27,942.942 INFO:teuthology.orchestra.run.plana001:Running: 'install -d -m0755 -- /home/ubuntu/cephtest/archive/coredump && sudo sysctl -w kernel.core_pattern=/home/ubuntu/cephtest/archive/coredump/%t.%p.core'
2018-10-26 18:37:28,033.033 INFO:teuthology.orchestra.run.plana001.stdout:kernel.core_pattern = /home/ubuntu/cephtest/archive/coredump/%t.%p.core
2018-10-26 18:37:28,034.034 INFO:teuthology.run_tasks:Running task internal.sudo...
2018-10-26 18:37:28,034.034 INFO:teuthology.task.internal:Configuring sudo...
2018-10-26 18:37:28,034.034 INFO:teuthology.orchestra.run.plana001:Running: "sudo sed -i.orig.teuthology -e 's/^\\([^#]*\\) \\(requiretty\\)/\\1 !\\2/g' -e 's/^\\([^#]*\\) !\\(visiblepw\\)/\\1 \\2/g' /etc/sudoers"
2018-10-26 18:37:28,122.122 INFO:teuthology.run_tasks:Running task internal.syslog...
2018-10-26 18:37:28,124.124 INFO:teuthology.run_tasks:Running task internal.timer...
2018-10-26 18:37:28,124.124 INFO:teuthology.task.internal:Starting timer...
2018-10-26 18:37:28,124.124 INFO:teuthology.run_tasks:Running task pcp...
2018-10-26 18:37:28,143.143 INFO:teuthology.run_tasks:Running task selinux...
2018-10-26 18:37:28,144.144 INFO:teuthology.orchestra.run.plana001:Running: 'sudo service auditd rotate'
2018-10-26 18:37:28,219.219 INFO:teuthology.orchestra.run.plana001.stdout:Rotating logs: [  OK  ]
2018-10-26 18:37:28,221.221 INFO:teuthology.orchestra.run.plana001:Running: '/usr/sbin/getenforce'
2018-10-26 18:37:28,299.299 INFO:teuthology.orchestra.run.plana001.stdout:Disabled
2018-10-26 18:37:28,300.300 INFO:teuthology.orchestra.run.plana001:Running: 'sudo grep \'avc: .*denied\' /var/log/audit/audit.log | grep -v \'\\(comm="dmidecode"\\|chronyd.service\\|name="cephtest"\\|scontext=system_u:system_r:nrpe_t:s0\\|scontext=system_u:system_r:pcp_pmlogger_t\\|scontext=system_u:system_r:pcp_pmcd_t:s0\\|comm="rhsmd"\\|scontext=system_u:system_r:syslogd_t:s0\\)\''
2018-10-26 18:37:28,385.385 INFO:teuthology.task.selinux:Putting SELinux into permissive mode
2018-10-26 18:37:28,386.386 INFO:teuthology.orchestra.run.plana001:Running: 'sudo /usr/sbin/setenforce permissive'
2018-10-26 18:37:28,471.471 INFO:teuthology.orchestra.run.plana001.stderr:/usr/sbin/setenforce: SELinux is disabled
2018-10-26 18:37:28,471.471 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/teuthology/teuthology/run_tasks.py", line 89, in run_tasks
    manager.__enter__()
  File "/home/teuthworker/teuthology/teuthology/task/__init__.py", line 122, in __enter__
    self.setup()
  File "/home/teuthworker/teuthology/teuthology/task/selinux.py", line 69, in setup
    self.set_mode()
  File "/home/teuthworker/teuthology/teuthology/task/selinux.py", line 98, in set_mode
    args=['sudo', '/usr/sbin/setenforce', self.mode],
  File "/home/teuthworker/teuthology/teuthology/orchestra/remote.py", line 193, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 429, in run
    r.wait()
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 161, in wait
    self._raise_for_status()
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 183, in _raise_for_status
    node=self.hostname, label=self.label
CommandFailedError: Command failed on plana001 with status 1: 'sudo /usr/sbin/setenforce permissive'
2018-10-26 18:37:28,472.472 INFO:teuthology.task.selinux:Restoring old SELinux modes
2018-10-26 18:37:28,472.472 INFO:teuthology.orchestra.run.plana001:Running: 'sudo /usr/sbin/setenforce disabled'
2018-10-26 18:37:28,561.561 INFO:teuthology.orchestra.run.plana001.stderr:/usr/sbin/setenforce: SELinux is disabled
2018-10-26 18:37:28,562.562 ERROR:teuthology.run_tasks:Manager failed: selinux
Traceback (most recent call last):
  File "/home/teuthworker/teuthology/teuthology/run_tasks.py", line 159, in run_tasks
    suppress = manager.__exit__(*exc_info)
  File "/home/teuthworker/teuthology/teuthology/task/__init__.py", line 136, in __exit__
    self.teardown()
  File "/home/teuthworker/teuthology/teuthology/task/selinux.py", line 142, in teardown
    self.restore_modes()
  File "/home/teuthworker/teuthology/teuthology/task/selinux.py", line 158, in restore_modes
    args=['sudo', '/usr/sbin/setenforce', mode],
  File "/home/teuthworker/teuthology/teuthology/orchestra/remote.py", line 193, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 429, in run
    r.wait()
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 161, in wait
    self._raise_for_status()
  File "/home/teuthworker/teuthology/teuthology/orchestra/run.py", line 183, in _raise_for_status
    node=self.hostname, label=self.label
CommandFailedError: Command failed on plana001 with status 1: 'sudo /usr/sbin/setenforce disabled'
2018-10-26 18:37:28,562.562 INFO:teuthology.task.internal:Duration was 0.437824 seconds
2018-10-26 18:37:28,562.562 INFO:teuthology.task.internal:Restoring /etc/sudoers...
2018-10-26 18:37:28,562.562 INFO:teuthology.orchestra.run.plana001:Running: 'sudo mv -f /etc/sudoers.orig.teuthology /etc/sudoers'
2018-10-26 18:37:28,646.646 INFO:teuthology.orchestra.run.plana001:Running: 'sudo sysctl -w kernel.core_pattern=core && rmdir --ignore-fail-on-non-empty -- /home/ubuntu/cephtest/archive/coredump'
2018-10-26 18:37:28,738.738 INFO:teuthology.orchestra.run.plana001.stdout:kernel.core_pattern = core
2018-10-26 18:37:28,739.739 INFO:teuthology.orchestra.run.plana001:Running: "if test '!' -e /home/ubuntu/cephtest/archive/coredump ; then echo OK ; fi"
2018-10-26 18:37:28,824.824 INFO:teuthology.orchestra.run.plana001.stdout:OK
2018-10-26 18:37:28,825.825 INFO:teuthology.task.internal:Removing archive directory...
2018-10-26 18:37:28,825.825 INFO:teuthology.orchestra.run.plana001:Running: 'rm -rf -- /home/ubuntu/cephtest/archive'
2018-10-26 18:37:28,903.903 INFO:teuthology.task.internal:Not uploading archives.
2018-10-26 18:37:28,904.904 INFO:teuthology.task.internal:Tidying up after the test...
2018-10-26 18:37:28,904.904 INFO:teuthology.orchestra.run.plana001:Running: 'find /home/ubuntu/cephtest -ls ; rmdir -- /home/ubuntu/cephtest'
2018-10-26 18:37:28,983.983 INFO:teuthology.orchestra.run.plana001.stdout:192949026    0 drwxr-xr-x   2 ubuntu   root            6 Oct 26 18:37 /home/ubuntu/cephtest
2018-10-26 18:37:28,986.986 INFO:teuthology.run:Summary data:
{duration: 0.437824010848999, failure_reason: 'Command failed on plana001 with status
    1: ''sudo /usr/sbin/setenforce permissive''', owner: teuthworker@teuthology-node-1.novalocal,
  status: fail, success: false}

2018-10-26 18:37:28,986.986 WARNING:teuthology.report:No job_id found; not reporting results
2018-10-26 18:37:28,986.986 INFO:teuthology.run:FAIL
```

I also log into the test machine
```
[root@plana001 ~]# getenforce 
Disabled
[root@plana001 ~]# 
[root@plana001 ~]# setenforce --help
setenforce: SELinux is disabled
[root@plana001 ~]# echo $?
1
[root@plana001 ~]# 
[root@plana001 ~]# 
[root@plana001 ~]# setenforce 0
setenforce: SELinux is disabled
[root@plana001 ~]# echo $?
1
[root@plana001 ~]# 
[root@plana001 ~]# 
[root@plana001 ~]# setenforce 1
setenforce: SELinux is disabled
[root@plana001 ~]# echo $?
1
```

**Comment by vasukulkarni** [comment]
Jenkins test this please

**Comment by vasukulkarni** [comment]
jenkins retest this please

**Comment by djgalloway** [comment]
jenkins test this please

**Comment by vasukulkarni** [comment]
will merge on Monday

**Comment by zenglg** [comment]
Thanks

**Pull request merged**
