### PR TITLE
teuthology/suite: extract match() for filtering jobs

### PR DESCRIPTION
**Pull request by tchaikov**
for better readablity

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
Not sure why we merged it without testing? @toabctl @tchaikov ?

**Comment by kshtsk** [comment]
@toabctl I'm not sure we have unit test for this function:
```
$ grep -r collect_jobs teuthology
teuthology/suite/run.py:    def collect_jobs(self, arch, configs, newest=False, limit=0):
teuthology/suite/run.py:        # added to the args in collect_jobs, but not filled until
teuthology/suite/run.py:                self.collect_jobs(arch, configs, self.args.newest, job_limit)
```

**Comment by tchaikov** [comment]
@kshtsk could you please define "testing"? i tested it locally.

**Comment by kshtsk** [comment]
@tchaikov you haven't mention in the comments that you tested this and which kind of testing...

For now, I usually run deploy test which, deploys teuthology cluster and schedules jobs, at least it allows to run basic system integration tests.

**Comment by tchaikov** [comment]
sorry, i will accompany the test steps in my PRs in future. can i run deploy test as well using the trigger phrase?

**Comment by kshtsk** [comment]
not sure it will work, since merge branch is deleted once the PR incorporated... but I can manually run it for master branch

**Comment by tchaikov** [comment]
@kshtsk i mean, in future, am i allowed to run the deploy test as you do? i thought it's a privilege.

**Comment by kshtsk** [comment]
I think yes... the thing is that is not giving a comment before the testing is over.
If you wish I can make it notifying that the testing is started.

**Comment by toabctl** [comment]
> Not sure why we merged it without testing? @toabctl @tchaikov ?

I just approved it :)

**Pull request merged**
