### PR TITLE
teuthology-kill jobs have not remove all in queue ,having one job in queue

### PR DESCRIPTION
**Pull request by yonghengdexin735**
Fixes:http://tracker.ceph.com/issues/16569

Signed-off-by: zhang.zezhu zhang.zezhu@zte.com.cn

### CODE REVIEW

**Comment by yonghengdexin735** [comment]
@andrewschoen hello, please review for me,thanks

**Comment by dmick** [comment]
@yonghengdexin735: could you please file a tracker issue reporting the actual bug?  I can't understand what you're fixing or how this code change fixes it from what you've said here, and we should have a record.

**Comment by yonghengdexin735** [comment]
@dmick please look for the tracker: [http://tracker.ceph.com/issues/16569](url), you can see my issue reporting.

**Comment by dmick** [comment]
We should either move forward on this PR or close it.  @yonghengdexin735, do you still believe this to be a problem?  If so, can you rebase and repush, which will cause the tests to run?

**Pull request closed without merging**
