### PR TITLE
requirements.txt: bump up cliff and other packages.

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
Ouch... this is a huge list of packages.

**Comment by kshtsk** [comment]
tests are failing

**Comment by tchaikov** [comment]
```
WARNING: autodoc: failed to import module 'beanstalk' from module 'teuthology'; the following exception was raised:
No module named 'beanstalkc'
WARNING: autodoc: failed to import module 'describe_tests' from module 'teuthology'; the following exception was raised:
No module named 'dateutil'
WARNING: autodoc: failed to import module 'kill' from module 'teuthology'; the following exception was raised:
No module named 'beanstalkc'
```

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
```
2020-07-01T16:36:37.304 INFO:teuthology.orchestra.run.target-pr-1529-001.stdout:Extra Packages for Enterprise Linux 8 - x86_64  7.0  B/s | 4.7 kB     11:31
2020-07-01T16:36:37.306 INFO:teuthology.orchestra.run.target-pr-1529-001.stderr:Failed to download metadata for repo 'epel'
2020-07-01T16:36:37.315 INFO:teuthology.orchestra.run.target-pr-1529-001.stderr:Error: Failed to download metadata for repo 'epel'
2020-07-01T16:36:37.366 DEBUG:teuthology.orchestra.run:got remote process result: 1
```
Not related, but I schedule another run to make sure we're good.

**Comment by kshtsk** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@tchaikov do you have an idea why jenkins can't find executor: 
```
(pending—Waiting for next available executor on ‘sepia&&bionic&&huge&&!xenial’)
```

**Comment by kshtsk** [comment]
The job is actually scheduled but, it does not report back anything:
```
caplog = <_pytest.logging.LogCaptureFixture object at 0x7fe396ff3828>

    def test_sh_progress(caplog):
        misc.sh("echo AB ; sleep 5 ; /bin/echo C", 2) == "ABC\n"
        records = caplog.records
        assert ':sh: ' in records[0].message
        assert 'AB' == records[1].message
        assert 'C' == records[2].message
        #
        # With a sleep 5 between the first and the second message,
        # there must be at least 2 seconds between the log record
        # of the first message and the log record of the second one
        #
>       t1 = datetime.strptime(records[1].asctime.split(',')[0], "%Y-%m-%d %H:%M:%S")
E       AttributeError: 'LogRecord' object has no attribute 'asctime'
```

**Comment by kshtsk** [comment]
https://jenkins.ceph.com/view/all/job/teuthology-pull-requests/1192/

**Comment by kshtsk** [comment]
there are still failures in unit tests

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
@tchaikov changing from pytest==3.7.1 to pytest==5.4.3 is a huge jump.

And in general is there a sense to bump so many packages at once?

**Comment by tchaikov** [comment]
> @tchaikov changing from pytest==3.7.1 to pytest==5.4.3 is a huge jump.
> 
> And in general is there a sense to bump so many packages at once?

no. i am not sure why `-P pass python-openstackclient` does not work. what i wanted is but to upgrade this package. and i wanted to avoid cherry-pick the related change.

**Comment by kshtsk** [comment]
> > @tchaikov changing from pytest==3.7.1 to pytest==5.4.3 is a huge jump.
> > And in general is there a sense to bump so many packages at once?
> 
> no. i am not sure why `-P pass python-openstackclient` does not work. what i wanted is but to upgrade this package. and i wanted to avoid cherry-pick the related change.

what is the package named `pass`?

**Comment by kshtsk** [comment]
something wrong with pip-tools again?

**Comment by tchaikov** [comment]
> something wrong with pip-tools again?

@kshtsk i think we should keep `requirements.in` for pinning packages. the requirements specified `setup.py` is too tolerant for our deployment usage, hence `pip-compile` always tries to generate the **latest** requirements.txt unless `setup.py` specifies a certain version of a required package.

i updated the PR.

**Comment by tchaikov** [comment]
@susebot run deploy

**Comment by kshtsk** [comment]
> > something wrong with pip-tools again?
> 
> @kshtsk i think we should keep `requirements.in` for pinning packages. the requirements specified `setup.py` is too tolerant for our deployment usage, hence `pip-compile` always tries to generate the **latest** requirements.txt unless `setup.py` specifies a certain version of a required package.
> 
> i updated the PR.

Shouldn't we revert requirements.in contents to:
```
-e .[orchestra,test]
```

**Comment by tchaikov** [comment]
> Shouldn't we revert requirements.in contents to:
> 
> ```
> -e .[orchestra,test]
> ```

no.

**Comment by kshtsk** [comment]
Ok, what will be the strategy to stick some package for the next time? Like updater requirements.in or setup.py or both? If so shouldn't we add these steps to the docs?

**Comment by tchaikov** [comment]
> Ok, what will be the strategy to stick some package for the next time? Like updater requirements.in or setup.py or both? If so shouldn't we add these steps to the docs?

i wanted to encode such things in one of my previous change, and you recommended to create `update-requirements.sh`. so i created it. and now, we are moving back to docs?

**Comment by kshtsk** [comment]
> > Ok, what will be the strategy to stick some package for the next time? Like updater requirements.in or setup.py or both? If so shouldn't we add these steps to the docs?
> 
> i wanted to encode such things in one of my previous change using document, and you recommended to create `update-requirements.sh`. so i created it. and now, we are moving back to docs?

I don't think you understood me correctly, we didn't have requirements.in containing any version restriction, now with this change we have, and usually it was enough to change `setup.py` in order to stick some package to particular version and rerun the update-requirements.sh. The requirements.in had only pointers which package groups to use, no you are changing it to manage versions, and no word in the docs that we need to modify it, that's why I ask. If you think it does not worth, then ok.

**Comment by tchaikov** [comment]
> > > Ok, what will be the strategy to stick some package for the next time? Like updater requirements.in or setup.py or both? If so shouldn't we add these steps to the docs?
> > 
> > 
> > i wanted to encode such things in one of my previous change using document, and you recommended to create `update-requirements.sh`. so i created it. and now, we are moving back to docs?
> 
> I don't think you understood me correctly, we didn't have requirements.in containing any version restriction, now with this change we have, and usually it was enough to change `setup.py` in order to stick some package to particular version and rerun the update-requirements.sh.

yes, all true. probably, i am just tired writing the document for one or two of us. but since you explicitly asked for it. so i updated the document.

> The requirements.in had only pointers which package groups to use, no you are changing it to manage versions, and no word in the docs that we need to modify it, that's why I ask. If you think it does not worth, then ok.

well, i think it was merely a workaround to avoid the repeatings. IMHO, it's not for keeping track of "package groups". my fault to make it a replicate of `requirements.txt` and i didn't want to change it to mange versions, so i change it to track the package specs to be in sync with those in `setup.py`.

**Comment by kshtsk** [comment]
> yes, all true. probably, i am just tired writing the document for one or two of us. but since you explicitly asked for it. so i updated the document.
> 

Thanks for adding it and I'm sorry making you bored, the problem is that it becomes more complicated and am honestly loosing clue how to deal with all this to make 3rd party tools like dependabot happy. Since you're owner of the PR I asked you for clarification. Anyways thanks for your patience.

> > The requirements.in had only pointers which package groups to use, no you are changing it to manage versions, and no word in the docs that we need to modify it, that's why I ask. If you think it does not worth, then ok.
> 
> well, i think it was merely a workaround to avoid the repeatings. IMHO, it's not for keeping track of "package groups". my fault making it a replicate of `requirements.txt` and i didn't want to change it to mange versions, so i change it to track the package specs to be in sync with those in `setup.py`.

Sorry if make another suggestion, if we have so much troubles with this pip-compile and requirements, maybe just drop it and track everything in the setup.py?

**Comment by tchaikov** [comment]
> 
> Sorry if make another suggestion, if we have so much troubles with this pip-compile and requirements, maybe just drop it and track everything in the setup.py?

please note, the goal of this change is to bump cliff to fix the upstream test failure, as a a failing test is the source of uncertainty and potentially bugs. because i don't want to edit `requirements.txt` manually, i chose to fix `requirements.txt` and how it is updated here. for me, i'd prefer fix the test failure first instead of start tracking everything in setup.py in this changeset.

**Comment by tchaikov** [comment]
@rzarzynski @cbodley could you help review this change?

**Comment by kshtsk** [comment]
@susebot run deploy

**Pull request merged**
