### PR TITLE
orchestra/opsys: add newer sle and leap versions

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@zmc would like to take a look at this PR, it is also fixes unit tests

**Comment by kshtsk** [comment]
@zmc do you understand why is it failing at https://jenkins.ceph.com/job/teuthology-pull-requests/2126/

**Comment by zmc** [comment]
@kshtsk actually yeah - https://github.com/ceph/teuthology/pull/1806 should be ready to merge, and fixes all the outstanding test issues that I could find

**Comment by kshtsk** [comment]
> @kshtsk actually yeah - #1806 should be ready to merge, and fixes all the outstanding test issues that I could find

approved the #1806, and waiting it's merged

**Review by zmc — APPROVED** [review]

**Pull request merged**
