### PR TITLE
Ignore few se denials in log parsing

### PR DESCRIPTION
**Pull request by vasukulkarni**
dmidecode intermittently appears in denial list causing the test to fail

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
This should include a bugzilla URL in both the commit message and a comment

**Comment by vasukulkarni** [comment]
Fixed and repushed

**Comment by zmc** [comment]
I still want URLs in both the commit message and a comment, please.

Seems like we should have a BZ for the chronyd issue, no?

**Comment by vasukulkarni** [comment]
@zmc I have added the url in both commit and in comments, there is only tracker for chronyd which was originally seen on centOS not a bz.

**Comment by zmc** [comment]
Thanks @vasukulkarni 

In the future if we have to add more of these, I'd like to do it in a nicer way. And put the comments *before* the code in question. But I won't block on those issues now so this doesn't get stalled for another month :)

**Comment by vasukulkarni** [comment]
thanks @zmc :) sure i think it makes sense to read comments first.

**Pull request merged**
