### PR TITLE
fetch more rerun parameters from last run

### PR DESCRIPTION
**Pull request by ideepika**
we only fetch seed and subset param's from previous reruns right now,
   this adds fetching ceph_branch, sha1, suite_branch, suite_repo as
   well from last ran job.

Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
I could image why we parse the log run log, but I would suggest to get rid of parsing the log and start generate some status file for a run in json/yaml format which can be easily parsed, with just a single line.

**Comment by kshtsk** [comment]
Any updates on this, if it is not actual already, just close maybe?

**Comment by ideepika** [comment]
sorry, could not update it recently, will do this week

**Comment by ideepika** [comment]
> sorry, could not update it recently, will do this week

can work on a fix and open a new PR, closing for now, thanks!

**Pull request closed without merging**
