### PR TITLE
ansible 4.2

### PR DESCRIPTION
**Pull request by zmc**
To fix our last remaining Dependabot security issue.

I created https://github.com/ceph/teuthology/pull/1754 to help test this.

### CODE REVIEW

**Comment by zmc** [comment]
A smoke job passed: https://pulpito.ceph.com/zack-2022-04-29_16:17:05-smoke-quincy-distro-default-smithi/
ansible.log here: http://qa-proxy.ceph.com/teuthology/zack-2022-04-29_16:17:05-smoke-quincy-distro-default-smithi/6814143/ansible.log

It looks like it's about time to move away from python 3.6, which for example in sepia would require upgrading the teuthology VM to at least 20.04.

@djgalloway out of curiosity what ansible version(s) are you using with ceph-cm-ansible for admin tasks?

**Comment by djgalloway** [comment]
> @djgalloway out of curiosity what ansible version(s) are you using with ceph-cm-ansible for admin tasks?

```
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dgalloway/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dgalloway/git/ceph/teuthology/virtualenv/lib/python3.6/site-packages/ansible
  executable location = /home/dgalloway/git/ceph/teuthology/virtualenv/bin/ansible
  python version = 3.6.9 (default, Dec  8 2021, 21:08:43) [GCC 8.4.0]
```

**Comment by kshtsk** [comment]
the patch has conflicts

**Comment by kshtsk** [comment]
This is over 2 years PR, closing for now.

**Pull request closed without merging**
